// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const businessOfferMappingsComponents: YmSchemaComponents = {
  AddOffersToArchiveDTO: {
    kind: "object",
    properties: {
      notArchivedOffers: {
        kind: "array",
        items: { kind: "ref", name: "AddOffersToArchiveErrorDTO" },
        nullable: true,
      },
    },
    required: [],
  },
  AddOffersToArchiveErrorDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      error: { kind: "ref", name: "AddOffersToArchiveErrorType" },
    },
    required: ["offerId", "error"],
  },
  AddOffersToArchiveErrorType: {
    kind: "string",
    enum: ["OFFER_HAS_STOCKS", "UNKNOWN"],
  },
  AddOffersToArchiveRequest: {
    kind: "object",
    properties: {
      offerIds: { kind: "array", items: { kind: "ref", name: "ShopSku" } },
    },
    required: ["offerIds"],
  },
  AddOffersToArchiveResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "AddOffersToArchiveDTO" },
    },
    required: ["status"],
  },
  AgeDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      ageUnit: { kind: "ref", name: "AgeUnitType" },
    },
    required: ["value", "ageUnit"],
  },
  AgeUnitType: { kind: "string", enum: ["YEAR", "MONTH"] },
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLockedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  BaseOfferAdult: { kind: "boolean" },
  BaseOfferBoxCount: { kind: "number", integer: true, minimum: 1 },
  BaseOfferCommodityCodes: {
    kind: "array",
    items: { kind: "ref", name: "CommodityCodeDTO" },
    nullable: true,
  },
  BaseOfferCustomsCommodityCode: { kind: "string" },
  BaseOfferDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      name: { kind: "ref", name: "OfferName" },
      marketCategoryId: { kind: "ref", name: "PartnerMarketCategoryId" },
      category: { kind: "ref", name: "OfferCategory" },
      pictures: {
        kind: "array",
        items: { kind: "ref", name: "Url" },
        nullable: true,
      },
      videos: {
        kind: "array",
        items: { kind: "ref", name: "Url" },
        nullable: true,
      },
      manuals: {
        kind: "array",
        items: { kind: "ref", name: "OfferManualDTO" },
        nullable: true,
      },
      vendor: { kind: "ref", name: "OfferVendor" },
      barcodes: { kind: "ref", name: "OfferBarcodes" },
      description: { kind: "ref", name: "OfferDescription" },
      manufacturerCountries: {
        kind: "ref",
        name: "BaseOfferManufacturerCountries",
      },
      weightDimensions: { kind: "ref", name: "OfferWeightDimensionsDTO" },
      vendorCode: { kind: "ref", name: "OfferVendorCode" },
      tags: { kind: "ref", name: "BaseOfferTags" },
      shelfLife: { kind: "ref", name: "TimePeriodDTO" },
      lifeTime: { kind: "ref", name: "TimePeriodDTO" },
      guaranteePeriod: { kind: "ref", name: "TimePeriodDTO" },
      customsCommodityCode: {
        kind: "ref",
        name: "BaseOfferCustomsCommodityCode",
      },
      commodityCodes: { kind: "ref", name: "BaseOfferCommodityCodes" },
      certificates: {
        kind: "array",
        items: { kind: "string" },
        nullable: true,
      },
      boxCount: { kind: "ref", name: "BaseOfferBoxCount" },
      condition: { kind: "ref", name: "OfferConditionDTO" },
      type: { kind: "ref", name: "OfferType" },
      downloadable: { kind: "ref", name: "BaseOfferDownloadable" },
      adult: { kind: "ref", name: "BaseOfferAdult" },
      age: { kind: "ref", name: "AgeDTO" },
      params: { kind: "ref", name: "BaseOfferParams" },
    },
    required: ["offerId"],
  },
  BaseOfferDownloadable: { kind: "boolean" },
  BaseOfferManufacturerCountries: {
    kind: "array",
    items: { kind: "string" },
    nullable: true,
  },
  BaseOfferParams: {
    kind: "array",
    items: { kind: "ref", name: "OfferParamDTO" },
    nullable: true,
  },
  BaseOfferResponseDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      name: { kind: "string" },
      marketCategoryId: { kind: "ref", name: "PartnerMarketCategoryId" },
      category: { kind: "ref", name: "OfferCategory" },
      pictures: {
        kind: "array",
        items: { kind: "ref", name: "Url" },
        nullable: true,
      },
      videos: {
        kind: "array",
        items: { kind: "ref", name: "Url" },
        nullable: true,
      },
      manuals: {
        kind: "array",
        items: { kind: "ref", name: "OfferManualDTO" },
        nullable: true,
      },
      vendor: { kind: "ref", name: "OfferVendor" },
      barcodes: { kind: "ref", name: "OfferBarcodes" },
      description: { kind: "string" },
      manufacturerCountries: {
        kind: "ref",
        name: "BaseOfferManufacturerCountries",
      },
      weightDimensions: { kind: "ref", name: "OfferWeightDimensionsDTO" },
      vendorCode: { kind: "ref", name: "OfferVendorCode" },
      tags: { kind: "ref", name: "BaseOfferTags" },
      shelfLife: { kind: "ref", name: "TimePeriodDTO" },
      lifeTime: { kind: "ref", name: "TimePeriodDTO" },
      guaranteePeriod: { kind: "ref", name: "TimePeriodDTO" },
      customsCommodityCode: {
        kind: "ref",
        name: "BaseOfferCustomsCommodityCode",
      },
      commodityCodes: { kind: "ref", name: "BaseOfferCommodityCodes" },
      certificates: {
        kind: "array",
        items: { kind: "string" },
        nullable: true,
      },
      boxCount: { kind: "ref", name: "BaseOfferBoxCount" },
      condition: { kind: "ref", name: "OfferConditionDTO" },
      type: { kind: "ref", name: "OfferType" },
      downloadable: { kind: "ref", name: "BaseOfferDownloadable" },
      adult: { kind: "ref", name: "BaseOfferAdult" },
      age: { kind: "ref", name: "AgeDTO" },
      params: { kind: "ref", name: "BaseOfferParams" },
    },
    required: ["offerId"],
  },
  BaseOfferTags: { kind: "array", items: { kind: "string" }, nullable: true },
  BasePriceDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  CampaignId: { kind: "number", integer: true, minimum: 1 },
  CatalogLanguageType: { kind: "string", enum: ["RU", "UZ"] },
  CommodityCodeDTO: {
    kind: "object",
    properties: {
      code: { kind: "string" },
      type: { kind: "ref", name: "CommodityCodeType" },
    },
    required: ["code", "type"],
  },
  CommodityCodeType: {
    kind: "string",
    enum: ["CUSTOMS_COMMODITY_CODE", "IKPU_CODE"],
  },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  DeleteOfferParameterType: {
    kind: "string",
    enum: [
      "ADDITIONAL_EXPENSES",
      "ADULT",
      "AGE",
      "BARCODES",
      "BOX_COUNT",
      "CERTIFICATES",
      "COMMODITY_CODES",
      "CONDITION",
      "CUSTOMS_COMMODITY_CODE",
      "DESCRIPTION",
      "DOWNLOADABLE",
      "GUARANTEE_PERIOD",
      "LIFE_TIME",
      "MANUALS",
      "MANUFACTURER_COUNTRIES",
      "PARAMETERS",
      "PICTURES",
      "PURCHASE_PRICE",
      "SHELF_LIFE",
      "TAGS",
      "TYPE",
      "VENDOR_CODE",
      "VIDEOS",
    ],
  },
  DeleteOffersDTO: {
    kind: "object",
    properties: {
      notDeletedOfferIds: {
        kind: "array",
        items: { kind: "ref", name: "ShopSku" },
        nullable: true,
      },
    },
    required: [],
  },
  DeleteOffersFromArchiveDTO: {
    kind: "object",
    properties: {
      notUnarchivedOfferIds: {
        kind: "array",
        items: { kind: "ref", name: "ShopSku" },
        nullable: true,
      },
    },
    required: [],
  },
  DeleteOffersFromArchiveRequest: {
    kind: "object",
    properties: {
      offerIds: { kind: "array", items: { kind: "ref", name: "ShopSku" } },
    },
    required: ["offerIds"],
  },
  DeleteOffersFromArchiveResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "DeleteOffersFromArchiveDTO" },
    },
    required: ["status"],
  },
  DeleteOffersRequest: {
    kind: "object",
    properties: {
      offerIds: { kind: "array", items: { kind: "ref", name: "ShopSku" } },
    },
    required: ["offerIds"],
  },
  DeleteOffersResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "DeleteOffersDTO" },
    },
    required: ["status"],
  },
  DiscountBase: { kind: "number", minimum: 0 },
  GenerateOfferBarcodesRequest: {
    kind: "object",
    properties: {
      offerIds: { kind: "array", items: { kind: "ref", name: "ShopSku" } },
      skipIfExists: { kind: "boolean" },
    },
    required: ["offerIds"],
  },
  GenerateOfferBarcodesResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GenerateOfferBarcodesResultDTO" },
    },
    required: ["status"],
  },
  GenerateOfferBarcodesResultDTO: {
    kind: "object",
    properties: {
      unprocessedOfferIds: {
        kind: "array",
        items: { kind: "ref", name: "ShopSku" },
      },
    },
    required: ["unprocessedOfferIds"],
  },
  GetMappingDTO: {
    kind: "object",
    properties: {
      marketSku: { kind: "ref", name: "MarketSku" },
      marketSkuName: { kind: "string" },
      marketModelName: { kind: "string" },
      marketCategoryId: { kind: "number", integer: true },
      marketCategoryName: { kind: "string" },
    },
    required: [],
  },
  GetOfferDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      name: { kind: "string" },
      marketCategoryId: { kind: "ref", name: "PartnerMarketCategoryId" },
      category: { kind: "ref", name: "OfferCategory" },
      pictures: {
        kind: "array",
        items: { kind: "ref", name: "Url" },
        nullable: true,
      },
      videos: {
        kind: "array",
        items: { kind: "ref", name: "Url" },
        nullable: true,
      },
      manuals: {
        kind: "array",
        items: { kind: "ref", name: "OfferManualDTO" },
        nullable: true,
      },
      vendor: { kind: "ref", name: "OfferVendor" },
      barcodes: { kind: "ref", name: "OfferBarcodes" },
      description: { kind: "string" },
      manufacturerCountries: {
        kind: "ref",
        name: "BaseOfferManufacturerCountries",
      },
      weightDimensions: { kind: "ref", name: "OfferWeightDimensionsDTO" },
      vendorCode: { kind: "ref", name: "OfferVendorCode" },
      tags: { kind: "ref", name: "BaseOfferTags" },
      shelfLife: { kind: "ref", name: "TimePeriodDTO" },
      lifeTime: { kind: "ref", name: "TimePeriodDTO" },
      guaranteePeriod: { kind: "ref", name: "TimePeriodDTO" },
      customsCommodityCode: {
        kind: "ref",
        name: "BaseOfferCustomsCommodityCode",
      },
      commodityCodes: { kind: "ref", name: "BaseOfferCommodityCodes" },
      certificates: {
        kind: "array",
        items: { kind: "string" },
        nullable: true,
      },
      boxCount: { kind: "ref", name: "BaseOfferBoxCount" },
      condition: { kind: "ref", name: "OfferConditionDTO" },
      type: { kind: "ref", name: "OfferType" },
      downloadable: { kind: "ref", name: "BaseOfferDownloadable" },
      adult: { kind: "ref", name: "BaseOfferAdult" },
      age: { kind: "ref", name: "AgeDTO" },
      params: { kind: "ref", name: "BaseOfferParams" },
      basicPrice: { kind: "ref", name: "GetPriceWithDiscountDTO" },
      purchasePrice: { kind: "ref", name: "GetPriceDTO" },
      additionalExpenses: { kind: "ref", name: "GetPriceDTO" },
      cardStatus: { kind: "ref", name: "OfferCardStatusType" },
      campaigns: {
        kind: "array",
        items: { kind: "ref", name: "OfferCampaignStatusDTO" },
        nullable: true,
      },
      sellingPrograms: {
        kind: "array",
        items: { kind: "ref", name: "OfferSellingProgramDTO" },
        nullable: true,
      },
      mediaFiles: { kind: "ref", name: "OfferMediaFilesDTO" },
      archived: { kind: "boolean" },
      groupId: { kind: "string" },
    },
    required: ["offerId"],
  },
  GetOfferMappingDTO: {
    kind: "object",
    properties: {
      offer: { kind: "ref", name: "GetOfferDTO" },
      mapping: { kind: "ref", name: "GetMappingDTO" },
      showcaseUrls: {
        kind: "array",
        items: { kind: "ref", name: "ShowcaseUrlDTO" },
        nullable: true,
      },
    },
    required: [],
  },
  GetOfferMappingsRequest: {
    kind: "object",
    properties: {
      offerIds: {
        kind: "array",
        items: { kind: "ref", name: "ShopSku" },
        nullable: true,
      },
      cardStatuses: {
        kind: "array",
        items: { kind: "ref", name: "OfferCardStatusType" },
        nullable: true,
      },
      categoryIds: {
        kind: "array",
        items: { kind: "number", integer: true, minimum: 0 },
        nullable: true,
      },
      vendorNames: { kind: "array", items: { kind: "string" }, nullable: true },
      tags: { kind: "array", items: { kind: "string" }, nullable: true },
      archived: { kind: "boolean" },
    },
    required: [],
  },
  GetOfferMappingsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GetOfferMappingsResultDTO" },
    },
    required: ["status"],
  },
  GetOfferMappingsResultDTO: {
    kind: "object",
    properties: {
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
      offerMappings: {
        kind: "array",
        items: { kind: "ref", name: "GetOfferMappingDTO" },
      },
    },
    required: ["offerMappings"],
  },
  GetPriceDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
      updatedAt: { kind: "string" },
    },
    required: ["value", "currencyId", "updatedAt"],
  },
  GetPriceWithDiscountDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
      discountBase: { kind: "ref", name: "DiscountBase" },
      updatedAt: { kind: "string" },
    },
    required: ["value", "currencyId", "updatedAt"],
  },
  MarketSku: { kind: "number", integer: true, minimum: 1 },
  MediaFileUploadStateType: {
    kind: "string",
    enum: ["UPLOADING", "UPLOADED", "FAILED"],
  },
  OfferBarcodes: { kind: "array", items: { kind: "string" }, nullable: true },
  OfferCampaignStatusDTO: {
    kind: "object",
    properties: {
      campaignId: { kind: "ref", name: "CampaignId" },
      status: { kind: "ref", name: "OfferCampaignStatusType" },
    },
    required: ["campaignId", "status"],
  },
  OfferCampaignStatusType: {
    kind: "string",
    enum: [
      "PUBLISHED",
      "CHECKING",
      "DISABLED_BY_PARTNER",
      "DISABLED_AUTOMATICALLY",
      "REJECTED_BY_MARKET",
      "CREATING_CARD",
      "NO_CARD",
      "NO_STOCKS",
      "ARCHIVED",
      "READY_FOR_PUBLICATION",
    ],
  },
  OfferCardStatusType: {
    kind: "string",
    enum: [
      "HAS_CARD_CAN_NOT_UPDATE",
      "HAS_CARD_CAN_UPDATE",
      "HAS_CARD_CAN_UPDATE_ERRORS",
      "HAS_CARD_CAN_UPDATE_PROCESSING",
      "NO_CARD_NEED_CONTENT",
      "NO_CARD_MARKET_WILL_CREATE",
      "NO_CARD_ERRORS",
      "NO_CARD_PROCESSING",
      "NO_CARD_ADD_TO_CAMPAIGN",
    ],
  },
  OfferCategory: { kind: "string" },
  OfferConditionDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "OfferConditionType" },
      quality: { kind: "ref", name: "OfferConditionQualityType" },
      reason: { kind: "string" },
    },
    required: [],
  },
  OfferConditionQualityType: {
    kind: "string",
    enum: ["PERFECT", "EXCELLENT", "GOOD", "NOT_SPECIFIED"],
  },
  OfferConditionType: {
    kind: "string",
    enum: [
      "PREOWNED",
      "SHOWCASESAMPLE",
      "REFURBISHED",
      "REDUCTION",
      "RENOVATED",
      "NOT_SPECIFIED",
    ],
  },
  OfferDescription: { kind: "string", maxLength: 6000 },
  OfferManualDTO: {
    kind: "object",
    properties: {
      url: { kind: "ref", name: "Url" },
      title: { kind: "string", maxLength: 500 },
    },
    required: ["url"],
  },
  OfferMappingErrorDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "OfferMappingErrorType" },
      parameterId: { kind: "number", integer: true },
      message: { kind: "string" },
    },
    required: ["type", "message"],
  },
  OfferMappingErrorType: {
    kind: "string",
    enum: [
      "UNKNOWN_CATEGORY",
      "INVALID_CATEGORY",
      "EMPTY_MARKET_CATEGORY",
      "UNKNOWN_PARAMETER",
      "UNEXPECTED_BOOLEAN_VALUE",
      "NUMBER_FORMAT",
      "INVALID_UNIT_ID",
      "INVALID_GROUP_ID_LENGTH",
      "INVALID_GROUP_ID_CHARACTERS",
      "INVALID_PICKER_URL",
      "LOCKED_DIMENSIONS",
      "INVALID_COMMODITY_CODE",
    ],
  },
  OfferMediaFileDTO: {
    kind: "object",
    properties: {
      url: { kind: "ref", name: "Url" },
      title: { kind: "string" },
      uploadState: { kind: "ref", name: "MediaFileUploadStateType" },
    },
    required: [],
  },
  OfferMediaFilesDTO: {
    kind: "object",
    properties: {
      firstVideoAsCover: { kind: "boolean" },
      videos: {
        kind: "array",
        items: { kind: "ref", name: "OfferMediaFileDTO" },
        nullable: true,
      },
      pictures: {
        kind: "array",
        items: { kind: "ref", name: "OfferMediaFileDTO" },
        nullable: true,
      },
      manuals: {
        kind: "array",
        items: { kind: "ref", name: "OfferMediaFileDTO" },
        nullable: true,
      },
    },
    required: [],
  },
  OfferName: { kind: "string", maxLength: 256 },
  OfferParamDTO: {
    kind: "object",
    properties: {
      name: { kind: "string", maxLength: 200 },
      value: { kind: "string" },
    },
    required: ["name", "value"],
  },
  OfferSellingProgramDTO: {
    kind: "object",
    properties: {
      sellingProgram: { kind: "ref", name: "SellingProgramType" },
      status: { kind: "ref", name: "OfferSellingProgramStatusType" },
    },
    required: ["sellingProgram", "status"],
  },
  OfferSellingProgramStatusType: { kind: "string", enum: ["FINE", "REJECT"] },
  OfferType: {
    kind: "string",
    enum: [
      "DEFAULT",
      "MEDICINE",
      "BOOK",
      "AUDIOBOOK",
      "ARTIST_TITLE",
      "ON_DEMAND",
      "ALCOHOL",
    ],
  },
  OfferVendor: { kind: "string" },
  OfferVendorCode: { kind: "string" },
  OfferWeightDimensionsDTO: {
    kind: "object",
    properties: {
      length: { kind: "number", minimum: 0 },
      width: { kind: "number", minimum: 0 },
      height: { kind: "number", minimum: 0 },
      weight: { kind: "number", minimum: 0 },
    },
    required: ["length", "width", "height", "weight"],
  },
  PackagingForwardScrollingPagerDTO: {
    kind: "object",
    properties: { nextPageToken: { kind: "string" } },
    required: [],
  },
  ParameterValueDTO: {
    kind: "object",
    properties: {
      parameterId: { kind: "number", integer: true, minimum: 1 },
      unitId: { kind: "number", integer: true },
      valueId: { kind: "number", integer: true },
      value: { kind: "string" },
    },
    required: ["parameterId"],
  },
  PartnerMarketCategoryId: { kind: "number", integer: true, minimum: 0 },
  PriceWithDiscountDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
      discountBase: { kind: "ref", name: "DiscountBase" },
    },
    required: ["value", "currencyId"],
  },
  SellingProgramType: {
    kind: "string",
    enum: ["FBY", "FBS", "DBS", "EXPRESS", "LAAS"],
  },
  ShopSku: { kind: "string", minLength: 1, maxLength: 255 },
  ShowcaseType: { kind: "string", enum: ["B2B", "B2C"] },
  ShowcaseUrlDTO: {
    kind: "object",
    properties: {
      showcaseType: { kind: "ref", name: "ShowcaseType" },
      showcaseUrl: { kind: "string" },
    },
    required: ["showcaseType", "showcaseUrl"],
  },
  TimePeriodDTO: {
    kind: "object",
    properties: {
      timePeriod: { kind: "number", integer: true },
      timeUnit: { kind: "ref", name: "TimeUnitType" },
      comment: { kind: "string", maxLength: 500 },
    },
    required: ["timePeriod", "timeUnit"],
  },
  TimeUnitType: {
    kind: "string",
    enum: ["HOUR", "DAY", "WEEK", "MONTH", "YEAR"],
  },
  UpdateMappingDTO: {
    kind: "object",
    properties: { marketSku: { kind: "ref", name: "MarketSku" } },
    required: [],
  },
  UpdateOfferDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      name: { kind: "ref", name: "OfferName" },
      marketCategoryId: { kind: "ref", name: "PartnerMarketCategoryId" },
      category: { kind: "ref", name: "OfferCategory" },
      pictures: {
        kind: "array",
        items: { kind: "ref", name: "Url" },
        nullable: true,
      },
      videos: {
        kind: "array",
        items: { kind: "ref", name: "Url" },
        nullable: true,
      },
      manuals: {
        kind: "array",
        items: { kind: "ref", name: "OfferManualDTO" },
        nullable: true,
      },
      vendor: { kind: "ref", name: "OfferVendor" },
      barcodes: { kind: "ref", name: "OfferBarcodes" },
      description: { kind: "ref", name: "OfferDescription" },
      manufacturerCountries: {
        kind: "ref",
        name: "BaseOfferManufacturerCountries",
      },
      weightDimensions: { kind: "ref", name: "OfferWeightDimensionsDTO" },
      vendorCode: { kind: "ref", name: "OfferVendorCode" },
      tags: { kind: "ref", name: "BaseOfferTags" },
      shelfLife: { kind: "ref", name: "TimePeriodDTO" },
      lifeTime: { kind: "ref", name: "TimePeriodDTO" },
      guaranteePeriod: { kind: "ref", name: "TimePeriodDTO" },
      customsCommodityCode: {
        kind: "ref",
        name: "BaseOfferCustomsCommodityCode",
      },
      commodityCodes: { kind: "ref", name: "BaseOfferCommodityCodes" },
      certificates: {
        kind: "array",
        items: { kind: "string" },
        nullable: true,
      },
      boxCount: { kind: "ref", name: "BaseOfferBoxCount" },
      condition: { kind: "ref", name: "OfferConditionDTO" },
      type: { kind: "ref", name: "OfferType" },
      downloadable: { kind: "ref", name: "BaseOfferDownloadable" },
      adult: { kind: "ref", name: "BaseOfferAdult" },
      age: { kind: "ref", name: "AgeDTO" },
      params: { kind: "ref", name: "BaseOfferParams" },
      parameterValues: {
        kind: "array",
        items: { kind: "ref", name: "ParameterValueDTO" },
        nullable: true,
      },
      basicPrice: { kind: "ref", name: "PriceWithDiscountDTO" },
      purchasePrice: { kind: "ref", name: "BasePriceDTO" },
      additionalExpenses: { kind: "ref", name: "BasePriceDTO" },
      firstVideoAsCover: { kind: "boolean" },
      deleteParameters: {
        kind: "array",
        items: { kind: "ref", name: "DeleteOfferParameterType" },
        nullable: true,
      },
    },
    required: ["offerId"],
  },
  UpdateOfferMappingDTO: {
    kind: "object",
    properties: {
      offer: { kind: "ref", name: "UpdateOfferDTO" },
      mapping: { kind: "ref", name: "UpdateMappingDTO" },
    },
    required: ["offer"],
  },
  UpdateOfferMappingResultDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "OfferMappingErrorDTO" },
        nullable: true,
      },
      warnings: {
        kind: "array",
        items: { kind: "ref", name: "OfferMappingErrorDTO" },
        nullable: true,
      },
    },
    required: ["offerId"],
  },
  UpdateOfferMappingsRequest: {
    kind: "object",
    properties: {
      offerMappings: {
        kind: "array",
        items: { kind: "ref", name: "UpdateOfferMappingDTO" },
      },
      onlyPartnerMediaContent: { kind: "boolean" },
    },
    required: ["offerMappings"],
  },
  UpdateOfferMappingsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      results: {
        kind: "array",
        items: { kind: "ref", name: "UpdateOfferMappingResultDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  UpdateTimeDTO: {
    kind: "object",
    properties: { updatedAt: { kind: "string" } },
    required: ["updatedAt"],
  },
  Url: { kind: "string", minLength: 1, maxLength: 2000 },
};
