// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const deliveryOptionsComponents: YmSchemaComponents = {
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  BasicOrderItemDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      count: { kind: "number", integer: true, minimum: 1, maximum: 1000 },
    },
    required: ["offerId", "count"],
  },
  CourierDeliveryOptionDTO: {
    kind: "object",
    properties: {
      deliveryDateInterval: { kind: "ref", name: "DeliveryDateIntervalDTO" },
      deliveryTimeInterval: { kind: "ref", name: "TimeIntervalDTO" },
      price: { kind: "ref", name: "DeliveryOptionPriceDTO" },
    },
    required: [
      "deliveryDateInterval",
      "deliveryTimeInterval",
      "paymentMethods",
      "price",
    ],
  },
  CourierDeliveryOptionsDTO: {
    kind: "object",
    properties: {
      courierDeliveryOptions: {
        kind: "array",
        items: { kind: "ref", name: "CourierDeliveryOptionDTO" },
      },
    },
    required: ["courierDeliveryOptions"],
  },
  CourierDeliveryParametersDTO: {
    kind: "object",
    properties: {
      fullAddress: { kind: "string", minLength: 1, maxLength: 512 },
    },
    required: ["fullAddress"],
  },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  CurrencyValueDTO: {
    kind: "object",
    properties: {
      value: { kind: "number" },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  DeliveryDateIntervalDTO: {
    kind: "object",
    properties: { fromDate: { kind: "string" }, toDate: { kind: "string" } },
    required: ["fromDate", "toDate"],
  },
  DeliveryOptionPriceDTO: {
    kind: "object",
    properties: {
      value: { kind: "number" },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  GetDeliveryOptionsDTO: {
    kind: "object",
    properties: {
      warehousesDeliveryOptions: {
        kind: "array",
        items: { kind: "ref", name: "WarehousesDeliveryOptionsDTO" },
      },
    },
    required: ["warehousesDeliveryOptions"],
  },
  GetDeliveryOptionsItemDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      count: { kind: "number", integer: true, minimum: 1, maximum: 1000 },
      warehouseId: { kind: "number", integer: true, minimum: 1 },
    },
    required: ["offerId", "count"],
  },
  GetDeliveryOptionsRequest: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "GetDeliveryOptionsItemDTO" },
      },
      pickupDelivery: { kind: "ref", name: "PickupDeliveryParametersDTO" },
      courierDelivery: { kind: "ref", name: "CourierDeliveryParametersDTO" },
    },
    required: ["items"],
  },
  GetDeliveryOptionsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GetDeliveryOptionsDTO" },
    },
    required: ["status"],
  },
  GetReturnDeliveryOptionsDTO: {
    kind: "object",
    properties: {
      pickupDelivery: { kind: "ref", name: "PickupReturnDeliveryOptionsDTO" },
    },
    required: ["pickupDelivery"],
  },
  GetReturnDeliveryOptionsRequest: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "BasicOrderItemDTO" },
      },
      pickupDelivery: { kind: "ref", name: "PickupDeliveryParametersDTO" },
    },
    required: ["items", "pickupDelivery"],
  },
  GetReturnDeliveryOptionsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GetReturnDeliveryOptionsDTO" },
    },
    required: ["status"],
  },
  LogisticPointId: { kind: "number", integer: true, minimum: 1 },
  PickupDeliveryOptionsDTO: {
    kind: "object",
    properties: {
      pickupOptions: {
        kind: "array",
        items: { kind: "ref", name: "PickupOptionsDTO" },
      },
    },
    required: ["pickupOptions"],
  },
  PickupDeliveryParametersDTO: {
    kind: "object",
    properties: {
      logisticPointsIds: {
        kind: "array",
        items: { kind: "ref", name: "LogisticPointId" },
      },
    },
    required: ["logisticPointsIds"],
  },
  PickupOptionDTO: {
    kind: "object",
    properties: {
      deliveryDateInterval: { kind: "ref", name: "DeliveryDateIntervalDTO" },
      price: { kind: "ref", name: "DeliveryOptionPriceDTO" },
    },
    required: ["deliveryDateInterval", "price"],
  },
  PickupOptionsDTO: {
    kind: "object",
    properties: {
      logisticPointId: { kind: "ref", name: "LogisticPointId" },
      options: {
        kind: "array",
        items: { kind: "ref", name: "PickupOptionDTO" },
      },
    },
    required: ["logisticPointId", "options", "paymentMethods"],
  },
  PickupReturnDeliveryOptionsDTO: {
    kind: "object",
    properties: {
      logisticPointIds: {
        kind: "array",
        items: { kind: "ref", name: "LogisticPointId" },
      },
    },
    required: ["logisticPointIds"],
  },
  ShopSku: { kind: "string", minLength: 1, maxLength: 255 },
  TimeIntervalDTO: {
    kind: "object",
    properties: { fromTime: { kind: "string" }, toTime: { kind: "string" } },
    required: ["fromTime", "toTime"],
  },
  WarehouseDeliveryOptionsDTO: {
    kind: "object",
    properties: {
      pickupDelivery: { kind: "ref", name: "PickupDeliveryOptionsDTO" },
      courierDelivery: { kind: "ref", name: "CourierDeliveryOptionsDTO" },
    },
    required: [],
  },
  WarehouseId: { kind: "number", integer: true, minimum: 1 },
  WarehousesDeliveryOptionsDTO: {
    kind: "object",
    properties: {
      warehouseId: { kind: "ref", name: "WarehouseId" },
      deliveryOptions: { kind: "ref", name: "WarehouseDeliveryOptionsDTO" },
      items: {
        kind: "array",
        items: { kind: "ref", name: "BasicOrderItemDTO" },
      },
    },
    required: ["warehouseId", "deliveryOptions", "items"],
  },
};
