// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const goodsStatsComponents: YmSchemaComponents = {
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  GetGoodsStatsRequest: {
    kind: "object",
    properties: {
      shopSkus: { kind: "array", items: { kind: "ref", name: "ShopSku" } },
    },
    required: ["shopSkus"],
  },
  GetGoodsStatsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GoodsStatsDTO" },
    },
    required: ["status"],
  },
  GoodsStatsDTO: {
    kind: "object",
    properties: {
      shopSkus: {
        kind: "array",
        items: { kind: "ref", name: "GoodsStatsGoodsDTO" },
      },
    },
    required: ["shopSkus"],
  },
  GoodsStatsGoodsDTO: {
    kind: "object",
    properties: {
      shopSku: { kind: "ref", name: "ShopSku" },
      marketSku: { kind: "ref", name: "MarketSku" },
      name: { kind: "string" },
      price: { kind: "number" },
      categoryId: { kind: "number", integer: true },
      categoryName: { kind: "string" },
      weightDimensions: { kind: "ref", name: "GoodsStatsWeightDimensionsDTO" },
      warehouses: {
        kind: "array",
        items: { kind: "ref", name: "GoodsStatsWarehouseDTO" },
        nullable: true,
      },
      tariffs: {
        kind: "array",
        items: { kind: "ref", name: "TariffDTO" },
        nullable: true,
      },
      pictures: {
        kind: "array",
        items: { kind: "ref", name: "Url" },
        nullable: true,
      },
    },
    required: [],
  },
  GoodsStatsWarehouseDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      name: { kind: "string" },
      stocks: {
        kind: "array",
        items: { kind: "ref", name: "WarehouseStockDTO" },
      },
    },
    required: ["stocks"],
  },
  GoodsStatsWeightDimensionsDTO: {
    kind: "object",
    properties: {
      length: { kind: "number" },
      width: { kind: "number" },
      height: { kind: "number" },
      weight: { kind: "number" },
    },
    required: [],
  },
  MarketSku: { kind: "number", integer: true, minimum: 1 },
  ShopSku: { kind: "string", minLength: 1, maxLength: 255 },
  TariffDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "TariffType" },
      percent: { kind: "number" },
      amount: { kind: "number" },
      currency: { kind: "ref", name: "CurrencyType" },
      parameters: {
        kind: "array",
        items: { kind: "ref", name: "TariffParameterDTO" },
      },
    },
    required: ["type", "amount", "currency", "parameters"],
  },
  TariffParameterDTO: {
    kind: "object",
    properties: { name: { kind: "string" }, value: { kind: "string" } },
    required: ["name", "value"],
  },
  TariffType: {
    kind: "string",
    enum: [
      "AGENCY_COMMISSION",
      "PAYMENT_TRANSFER",
      "STORAGE",
      "WITHDRAW",
      "SURPLUS",
      "FEE",
      "DELIVERY_TO_CUSTOMER",
      "CROSSREGIONAL_DELIVERY",
      "CROSSREGIONAL_DELIVERY_RETURN",
      "DISPOSAL",
      "SORTING_CENTER_STORAGE",
      "EXPRESS_DELIVERY",
      "FF_XDOC_SUPPLY_BOX",
      "FF_XDOC_SUPPLY_PALLET",
      "SORTING",
      "MIDDLE_MILE",
      "RETURN_PROCESSING",
      "EXPRESS_CANCELLED_BY_PARTNER",
      "CROSSBORDER_DELIVERY",
      "INTAKE_SORTING_BULKY_CARGO",
      "INTAKE_SORTING_SMALL_GOODS",
      "INTAKE_SORTING_DAILY",
      "FF_STORAGE_BILLING",
      "CANCELLED_ORDER_FEE_QI",
      "LATE_ORDER_EXECUTION_FEE_QI",
      "VOLUME_STORAGE",
      "GOODS_ACCEPTANCE",
      "CARGO_ACCEPTANCE",
      "ORDER_PROCESSING",
      "WITHDRAW_EXTERNAL",
      "ITEM_BOOKING",
    ],
  },
  Url: { kind: "string", minLength: 1, maxLength: 2000 },
  WarehouseStockDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "WarehouseStockType" },
      count: { kind: "number", integer: true },
    },
    required: ["type", "count"],
  },
  WarehouseStockType: {
    kind: "string",
    enum: [
      "FIT",
      "FREEZE",
      "AVAILABLE",
      "QUARANTINE",
      "UTILIZATION",
      "DEFECT",
      "EXPIRED",
    ],
  },
};
