// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const offersComponents: YmSchemaComponents = {
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLockedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  BaseCampaignOfferDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      available: { kind: "boolean" },
    },
    required: ["offerId"],
  },
  BasePriceDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  DeleteCampaignOffersDTO: {
    kind: "object",
    properties: {
      notDeletedOfferIds: {
        kind: "array",
        items: { kind: "ref", name: "ShopSku" },
        nullable: true,
      },
    },
    required: [],
  },
  DeleteCampaignOffersRequest: {
    kind: "object",
    properties: {
      offerIds: { kind: "array", items: { kind: "ref", name: "ShopSku" } },
    },
    required: ["offerIds"],
  },
  DeleteCampaignOffersResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "DeleteCampaignOffersDTO" },
    },
    required: ["status"],
  },
  DiscountBase: { kind: "number", minimum: 0 },
  EmptyApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  GetCampaignOfferDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      available: { kind: "boolean" },
      basicPrice: { kind: "ref", name: "GetPriceWithDiscountDTO" },
      campaignPrice: { kind: "ref", name: "GetPriceWithVatDTO" },
      status: { kind: "ref", name: "OfferCampaignStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "OfferErrorDTO" },
        nullable: true,
      },
      warnings: {
        kind: "array",
        items: { kind: "ref", name: "OfferErrorDTO" },
        nullable: true,
      },
    },
    required: ["offerId"],
  },
  GetCampaignOffersRequest: {
    kind: "object",
    properties: {
      offerIds: {
        kind: "array",
        items: { kind: "ref", name: "ShopSku" },
        nullable: true,
      },
      statuses: {
        kind: "array",
        items: { kind: "ref", name: "OfferCampaignStatusType" },
        nullable: true,
      },
      categoryIds: {
        kind: "array",
        items: { kind: "number", integer: true, minimum: 0 },
        nullable: true,
      },
      vendorNames: { kind: "array", items: { kind: "string" }, nullable: true },
      tags: { kind: "array", items: { kind: "string" }, nullable: true },
    },
    required: [],
  },
  GetCampaignOffersResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GetCampaignOffersResultDTO" },
    },
    required: ["status"],
  },
  GetCampaignOffersResultDTO: {
    kind: "object",
    properties: {
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
      offers: {
        kind: "array",
        items: { kind: "ref", name: "GetCampaignOfferDTO" },
      },
    },
    required: ["offers"],
  },
  GetOfferRecommendationsRequest: {
    kind: "object",
    properties: {
      offerIds: {
        kind: "array",
        items: { kind: "ref", name: "ShopSku" },
        nullable: true,
      },
      competitivenessFilter: { kind: "ref", name: "PriceCompetitivenessType" },
    },
    required: [],
  },
  GetOfferRecommendationsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "OfferRecommendationsResultDTO" },
    },
    required: ["status"],
  },
  GetPriceWithDiscountDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
      discountBase: { kind: "ref", name: "DiscountBase" },
      updatedAt: { kind: "string" },
    },
    required: ["value", "currencyId", "updatedAt"],
  },
  GetPriceWithVatDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      discountBase: { kind: "ref", name: "DiscountBase" },
      currencyId: { kind: "ref", name: "CurrencyType" },
      vat: { kind: "ref", name: "VatType" },
      updatedAt: { kind: "string" },
    },
    required: ["updatedAt"],
  },
  OfferCampaignStatusType: {
    kind: "string",
    enum: [
      "PUBLISHED",
      "CHECKING",
      "DISABLED_BY_PARTNER",
      "DISABLED_AUTOMATICALLY",
      "REJECTED_BY_MARKET",
      "CREATING_CARD",
      "NO_CARD",
      "NO_STOCKS",
      "ARCHIVED",
      "READY_FOR_PUBLICATION",
    ],
  },
  OfferErrorDTO: {
    kind: "object",
    properties: { message: { kind: "string" }, comment: { kind: "string" } },
    required: [],
  },
  OfferForRecommendationDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      price: { kind: "ref", name: "BasePriceDTO" },
      competitiveness: { kind: "ref", name: "PriceCompetitivenessType" },
      shows: { kind: "number", integer: true },
    },
    required: [],
  },
  OfferRecommendationDTO: {
    kind: "object",
    properties: {
      offer: { kind: "ref", name: "OfferForRecommendationDTO" },
      recommendation: { kind: "ref", name: "OfferRecommendationInfoDTO" },
    },
    required: [],
  },
  OfferRecommendationInfoDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      competitivenessThresholds: {
        kind: "ref",
        name: "PriceCompetitivenessThresholdsDTO",
      },
    },
    required: [],
  },
  OfferRecommendationsResultDTO: {
    kind: "object",
    properties: {
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
      offerRecommendations: {
        kind: "array",
        items: { kind: "ref", name: "OfferRecommendationDTO" },
      },
    },
    required: ["offerRecommendations"],
  },
  PackagingForwardScrollingPagerDTO: {
    kind: "object",
    properties: { nextPageToken: { kind: "string" } },
    required: [],
  },
  PriceCompetitivenessThresholdsDTO: {
    kind: "object",
    properties: {
      optimalPrice: { kind: "ref", name: "BasePriceDTO" },
      averagePrice: { kind: "ref", name: "BasePriceDTO" },
    },
    required: [],
  },
  PriceCompetitivenessType: {
    kind: "string",
    enum: ["OPTIMAL", "AVERAGE", "LOW"],
  },
  PriceDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      discountBase: { kind: "ref", name: "DiscountBase" },
      currencyId: { kind: "ref", name: "CurrencyType" },
      vat: { kind: "ref", name: "VatType" },
    },
    required: [],
  },
  PriceWithDiscountDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
      discountBase: { kind: "ref", name: "DiscountBase" },
    },
    required: ["value", "currencyId"],
  },
  ShopSku: { kind: "string", minLength: 1, maxLength: 255 },
  UpdateCampaignOfferDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      available: { kind: "boolean" },
      vat: { kind: "ref", name: "VatType" },
    },
    required: ["offerId"],
  },
  UpdateCampaignOffersRequest: {
    kind: "object",
    properties: {
      offers: {
        kind: "array",
        items: { kind: "ref", name: "UpdateCampaignOfferDTO" },
      },
    },
    required: ["offers"],
  },
  UpdateTimeDTO: {
    kind: "object",
    properties: { updatedAt: { kind: "string" } },
    required: ["updatedAt"],
  },
  VatType: { kind: "number", integer: true },
};
