// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const ordersStatsComponents: YmSchemaComponents = {
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  GetOrdersStatsRequest: {
    kind: "object",
    properties: {
      dateFrom: { kind: "string" },
      dateTo: { kind: "string" },
      updateFrom: { kind: "string" },
      updateTo: { kind: "string" },
      orders: {
        kind: "array",
        items: { kind: "number", integer: true },
        nullable: true,
      },
      statuses: {
        kind: "array",
        items: { kind: "ref", name: "OrderStatsStatusType" },
        nullable: true,
      },
      hasCis: { kind: "boolean" },
    },
    required: [],
  },
  GetOrdersStatsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "OrdersStatsDTO" },
    },
    required: ["status"],
  },
  MarketSku: { kind: "number", integer: true, minimum: 1 },
  OrderStatsStatusType: {
    kind: "string",
    enum: [
      "CANCELLED_BEFORE_PROCESSING",
      "CANCELLED_IN_DELIVERY",
      "CANCELLED_IN_PROCESSING",
      "DELIVERY",
      "DELIVERED",
      "PARTIALLY_DELIVERED",
      "PARTIALLY_RETURNED",
      "PENDING",
      "PICKUP",
      "PROCESSING",
      "RESERVED",
      "RETURNED",
      "UNKNOWN",
      "UNPAID",
      "LOST",
    ],
  },
  OrdersStatsCommissionDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "OrdersStatsCommissionType" },
      actual: { kind: "number" },
    },
    required: [],
  },
  OrdersStatsCommissionType: {
    kind: "string",
    enum: [
      "FEE",
      "FULFILLMENT",
      "LOYALTY_PARTICIPATION_FEE",
      "AUCTION_PROMOTION",
      "INSTALLMENT",
      "DELIVERY_TO_CUSTOMER",
      "EXPRESS_DELIVERY_TO_CUSTOMER",
      "AGENCY",
      "PAYMENT_TRANSFER",
      "RETURNED_ORDERS_STORAGE",
      "SORTING",
      "INTAKE_SORTING",
      "RETURN_PROCESSING",
      "ILLIQUID_GOODS_SALE",
      "CROSSREGIONAL_DELIVERY",
      "FULFILLMENT_WITHDRAW",
      "ITEM_BOOKING",
    ],
  },
  OrdersStatsDTO: {
    kind: "object",
    properties: {
      orders: {
        kind: "array",
        items: { kind: "ref", name: "OrdersStatsOrderDTO" },
      },
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
    },
    required: ["orders"],
  },
  OrdersStatsDeliveryRegionDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      name: { kind: "string" },
    },
    required: [],
  },
  OrdersStatsDetailsDTO: {
    kind: "object",
    properties: {
      itemStatus: { kind: "ref", name: "OrdersStatsItemStatusType" },
      itemCount: { kind: "number", integer: true },
      updateDate: { kind: "string" },
      stockType: { kind: "ref", name: "OrdersStatsStockType" },
    },
    required: [],
  },
  OrdersStatsItemDTO: {
    kind: "object",
    properties: {
      offerName: { kind: "string" },
      marketSku: { kind: "ref", name: "MarketSku" },
      shopSku: { kind: "ref", name: "ShopSku" },
      count: { kind: "number", integer: true },
      prices: {
        kind: "array",
        items: { kind: "ref", name: "OrdersStatsPriceDTO" },
        nullable: true,
      },
      warehouse: { kind: "ref", name: "OrdersStatsWarehouseDTO" },
      details: {
        kind: "array",
        items: { kind: "ref", name: "OrdersStatsDetailsDTO" },
        nullable: true,
      },
      cisList: { kind: "array", items: { kind: "string" }, nullable: true },
      initialCount: { kind: "number", integer: true },
      bidFee: { kind: "number", integer: true, minimum: 0, maximum: 10000 },
      cofinanceThreshold: { kind: "number" },
      cofinanceValue: { kind: "number" },
    },
    required: [],
  },
  OrdersStatsItemStatusType: { kind: "string", enum: ["REJECTED", "RETURNED"] },
  OrdersStatsOrderDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      creationDate: { kind: "string" },
      statusUpdateDate: { kind: "string" },
      status: { kind: "ref", name: "OrderStatsStatusType" },
      partnerOrderId: { kind: "string" },
      paymentType: { kind: "ref", name: "OrdersStatsOrderPaymentType" },
      fake: { kind: "boolean" },
      deliveryRegion: { kind: "ref", name: "OrdersStatsDeliveryRegionDTO" },
      items: {
        kind: "array",
        items: { kind: "ref", name: "OrdersStatsItemDTO" },
      },
      initialItems: {
        kind: "array",
        items: { kind: "ref", name: "OrdersStatsItemDTO" },
        nullable: true,
      },
      payments: {
        kind: "array",
        items: { kind: "ref", name: "OrdersStatsPaymentDTO" },
      },
      commissions: {
        kind: "array",
        items: { kind: "ref", name: "OrdersStatsCommissionDTO" },
      },
      subsidies: {
        kind: "array",
        items: { kind: "ref", name: "OrdersStatsSubsidyDTO" },
        nullable: true,
      },
      currency: { kind: "ref", name: "CurrencyType" },
    },
    required: ["items", "payments", "commissions", "currency"],
  },
  OrdersStatsOrderPaymentType: {
    kind: "string",
    enum: ["POSTPAID", "PREPAID", "UNKNOWN"],
  },
  OrdersStatsPaymentDTO: {
    kind: "object",
    properties: {
      id: { kind: "string" },
      date: { kind: "string" },
      type: { kind: "ref", name: "OrdersStatsPaymentType" },
      source: { kind: "ref", name: "OrdersStatsPaymentSourceType" },
      total: { kind: "number" },
      paymentOrder: { kind: "ref", name: "OrdersStatsPaymentOrderDTO" },
    },
    required: [],
  },
  OrdersStatsPaymentOrderDTO: {
    kind: "object",
    properties: { id: { kind: "string" }, date: { kind: "string" } },
    required: [],
  },
  OrdersStatsPaymentSourceType: {
    kind: "string",
    enum: ["BUYER", "CASHBACK", "MARKETPLACE", "MARKET_CESSION", "SPLIT"],
  },
  OrdersStatsPaymentType: { kind: "string", enum: ["PAYMENT", "REFUND"] },
  OrdersStatsPriceDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "OrdersStatsPriceType" },
      costPerItem: { kind: "number" },
      total: { kind: "number" },
    },
    required: [],
  },
  OrdersStatsPriceType: {
    kind: "string",
    enum: ["BUYER", "CASHBACK", "MARKETPLACE"],
  },
  OrdersStatsStockType: { kind: "string", enum: ["FIT", "DEFECT", "EXPIRED"] },
  OrdersStatsSubsidyDTO: {
    kind: "object",
    properties: {
      operationType: { kind: "ref", name: "OrdersStatsSubsidyOperationType" },
      type: { kind: "ref", name: "OrdersStatsSubsidyType" },
      amount: { kind: "number" },
    },
    required: ["operationType", "type", "amount"],
  },
  OrdersStatsSubsidyOperationType: {
    kind: "string",
    enum: ["ACCRUAL", "DEDUCTION"],
  },
  OrdersStatsSubsidyType: {
    kind: "string",
    enum: ["YANDEX_CASHBACK", "SUBSIDY", "DELIVERY"],
  },
  OrdersStatsWarehouseDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      name: { kind: "string" },
    },
    required: [],
  },
  PackagingForwardScrollingPagerDTO: {
    kind: "object",
    properties: { nextPageToken: { kind: "string" } },
    required: [],
  },
  ShopSku: { kind: "string", minLength: 1, maxLength: 255 },
};
