// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const ordersComponents: YmSchemaComponents = {
  AcceptOrderCancellationRequest: {
    kind: "object",
    properties: {
      accepted: { kind: "boolean" },
      reason: { kind: "ref", name: "OrderCancellationReasonType" },
    },
    required: ["accepted"],
  },
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  BasePriceDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  BasicCourierDeliveryAddressDTO: {
    kind: "object",
    properties: {
      fullAddress: { kind: "string", minLength: 1, maxLength: 512 },
    },
    required: ["fullAddress"],
  },
  BasicOrderItemDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      count: { kind: "number", integer: true, minimum: 1, maximum: 1000 },
    },
    required: ["offerId", "count"],
  },
  BriefOrderItemDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      vat: { kind: "ref", name: "OrderVatType" },
      count: { kind: "number", integer: true },
      price: { kind: "number" },
      offerName: { kind: "string" },
      offerId: { kind: "ref", name: "ShopSku" },
      instances: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemInstanceDTO" },
        nullable: true,
      },
    },
    required: [],
  },
  BriefOrderItemInstanceDTO: {
    kind: "object",
    properties: {
      cis: { kind: "ref", name: "Cis" },
      uin: { kind: "string" },
      rnpt: { kind: "string" },
      gtd: { kind: "string" },
      countryCode: { kind: "ref", name: "CountryCode" },
    },
    required: [],
  },
  BusinessOrderBoxLayoutDTO: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "BusinessOrderBoxLayoutItemDTO" },
      },
      boxId: { kind: "number", integer: true },
      barcode: { kind: "string" },
    },
    required: ["items", "boxId", "barcode"],
  },
  BusinessOrderBoxLayoutItemDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      fullCount: { kind: "number", integer: true, minimum: 1 },
      partialCount: {
        kind: "ref",
        name: "BusinessOrderBoxLayoutPartialCountDTO",
      },
      instances: {
        kind: "array",
        items: { kind: "ref", name: "BriefOrderItemInstanceDTO" },
        nullable: true,
      },
    },
    required: ["id"],
  },
  BusinessOrderBoxLayoutPartialCountDTO: {
    kind: "object",
    properties: {
      current: { kind: "number", integer: true, minimum: 1 },
      total: { kind: "number", integer: true, minimum: 2 },
    },
    required: ["current", "total"],
  },
  BusinessOrderCourierDeliveryDTO: {
    kind: "object",
    properties: {
      address: { kind: "ref", name: "BusinessOrderDeliveryAddressDTO" },
      region: { kind: "ref", name: "RegionDTO" },
    },
    required: [],
  },
  BusinessOrderDTO: {
    kind: "object",
    properties: {
      orderId: { kind: "number", integer: true },
      campaignId: { kind: "ref", name: "CampaignId" },
      programType: { kind: "ref", name: "SellingProgramType" },
      externalOrderId: { kind: "ref", name: "ExternalOrderId" },
      status: { kind: "ref", name: "OrderStatusType" },
      substatus: { kind: "ref", name: "OrderSubstatusType" },
      creationDate: { kind: "string" },
      updateDate: { kind: "string" },
      paymentType: { kind: "ref", name: "OrderPaymentType" },
      paymentMethod: { kind: "ref", name: "OrderPaymentMethodType" },
      fake: { kind: "boolean" },
      items: {
        kind: "array",
        items: { kind: "ref", name: "BusinessOrderItemDTO" },
      },
      prices: { kind: "ref", name: "OrderPriceDTO" },
      delivery: { kind: "ref", name: "BusinessOrderDeliveryDTO" },
      services: { kind: "ref", name: "BusinessOrderServicesDTO" },
      buyerType: { kind: "ref", name: "OrderBuyerType" },
      notes: { kind: "string" },
      cancelRequested: { kind: "boolean" },
      sourcePlatform: { kind: "ref", name: "OrderSourcePlatformType" },
    },
    required: [
      "orderId",
      "campaignId",
      "status",
      "substatus",
      "creationDate",
      "paymentType",
      "paymentMethod",
      "fake",
      "items",
      "delivery",
    ],
  },
  BusinessOrderDeliveryAddressDTO: {
    kind: "object",
    properties: {
      country: { kind: "string" },
      postcode: { kind: "string" },
      city: { kind: "string" },
      district: { kind: "string" },
      subway: { kind: "string" },
      street: { kind: "string" },
      house: { kind: "string" },
      block: { kind: "string" },
      entrance: { kind: "string" },
      entryphone: { kind: "string" },
      floor: { kind: "string" },
      apartment: { kind: "string" },
      gps: { kind: "ref", name: "GpsDTO" },
    },
    required: [],
  },
  BusinessOrderDeliveryDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "OrderDeliveryType" },
      serviceName: { kind: "string" },
      deliveryServiceId: { kind: "number", integer: true },
      warehouseId: { kind: "string" },
      deliveryPartnerType: { kind: "ref", name: "OrderDeliveryPartnerType" },
      dispatchType: { kind: "ref", name: "OrderDeliveryDispatchType" },
      dates: { kind: "ref", name: "BusinessOrderDeliveryDatesDTO" },
      shipment: { kind: "ref", name: "BusinessOrderShipmentDTO" },
      courier: { kind: "ref", name: "BusinessOrderCourierDeliveryDTO" },
      pickup: { kind: "ref", name: "BusinessOrderPickupDeliveryDTO" },
      transfer: { kind: "ref", name: "BusinessOrderTransferDTO" },
      boxesLayout: {
        kind: "array",
        items: { kind: "ref", name: "BusinessOrderBoxLayoutDTO" },
        nullable: true,
      },
      tracks: {
        kind: "array",
        items: { kind: "ref", name: "OrderTrackDTO" },
        nullable: true,
      },
      estimated: { kind: "boolean" },
      receiveBarcode: { kind: "string" },
      receiveCode: { kind: "string" },
      digitalGoods: { kind: "ref", name: "DigitalGoodsDeliveryDetailsDTO" },
    },
    required: [
      "type",
      "serviceName",
      "deliveryServiceId",
      "deliveryPartnerType",
      "dates",
    ],
  },
  BusinessOrderDeliveryDatesDTO: {
    kind: "object",
    properties: {
      fromDate: { kind: "string" },
      toDate: { kind: "string" },
      fromTime: { kind: "string" },
      toTime: { kind: "string" },
      realDeliveryDate: { kind: "string" },
    },
    required: ["fromDate"],
  },
  BusinessOrderEacDTO: {
    kind: "object",
    properties: {
      eacType: { kind: "ref", name: "OrderDeliveryEacType" },
      eacCode: { kind: "string" },
    },
    required: ["eacType"],
  },
  BusinessOrderItemDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      offerId: { kind: "ref", name: "ShopSku" },
      offerName: { kind: "string" },
      count: { kind: "number", integer: true },
      prices: { kind: "ref", name: "ItemPriceDTO" },
      instances: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemInstanceDTO" },
        nullable: true,
      },
      requiredInstanceTypes: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemInstanceType" },
        nullable: true,
      },
      itemStatuses: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemUnitStatusDTO" },
        nullable: true,
      },
      tags: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemTagType" },
        nullable: true,
      },
    },
    required: ["id", "offerId", "offerName", "count"],
  },
  BusinessOrderPickupDeliveryDTO: {
    kind: "object",
    properties: {
      address: { kind: "ref", name: "BusinessOrderDeliveryAddressDTO" },
      region: { kind: "ref", name: "RegionDTO" },
      logisticPointId: { kind: "ref", name: "LogisticPointId" },
      outletCode: { kind: "string" },
      outletStorageLimitDate: { kind: "string" },
    },
    required: [],
  },
  BusinessOrderServicesDTO: {
    kind: "object",
    properties: { liftType: { kind: "ref", name: "OrderLiftType" } },
    required: [],
  },
  BusinessOrderShipmentDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true, nullable: true },
      shipmentDate: { kind: "string" },
      shipmentTime: { kind: "string", nullable: true },
    },
    required: ["shipmentDate"],
  },
  BusinessOrderTransferDTO: {
    kind: "object",
    properties: {
      courier: { kind: "ref", name: "OrderCourierDTO" },
      eac: { kind: "ref", name: "BusinessOrderEacDTO" },
    },
    required: [],
  },
  CampaignId: { kind: "number", integer: true, minimum: 1 },
  Cis: { kind: "string" },
  CisDTO: {
    kind: "object",
    properties: {
      value: { kind: "string" },
      status: { kind: "ref", name: "CisStatusType" },
      substatus: { kind: "ref", name: "CisSubstatusType" },
      crptRequestId: { kind: "string" },
      crptRequestDateTime: { kind: "string" },
    },
    required: ["value", "status"],
  },
  CisStatusType: {
    kind: "string",
    enum: ["OK", "FAILED", "IN_PROGRESS", "INVALID", "NOT_ON_VALIDATION"],
  },
  CisSubstatusType: {
    kind: "string",
    enum: [
      "WRONG_OWNER_INN",
      "CIS_VALIDATION_ERROR",
      "CIS_GTIN_NOT_FOUND",
      "CIS_SERIAL_NUMBER_NOT_FOUND",
      "INVALID_SYMBOLS_FOUND",
      "CRYPTO_TAIL_FORMAT_MISMATCH_CIS_TYPE",
      "INVALID_CRYPTO_TAIL",
      "INVALID_CRYPTO_KEY",
      "VERIFICATION_FAILED_IN_EMITTER_COUNTRY",
      "UNSUPPORTED_AI_FOUND",
      "CIS_NOT_FOUND_IN_GIS_MT",
      "NOT_PLACED_ON_MARKET",
      "NOT_PRINTED_ON_PACKAGE",
      "EXPIRED_ITEM",
      "SALE_BLOCKED_BY_OGB",
      "ITEM_SOLD",
    ],
  },
  CountryCode: { kind: "string", minLength: 2, maxLength: 2 },
  CourierDeliveryAddressDTO: {
    kind: "object",
    properties: {
      fullAddress: { kind: "string", minLength: 1, maxLength: 512 },
      entrance: { kind: "string", minLength: 1, maxLength: 16 },
      floor: { kind: "number", integer: true },
      apartment: { kind: "string", minLength: 1, maxLength: 16 },
    },
    required: ["fullAddress"],
  },
  CreateOrderDTO: {
    kind: "object",
    properties: {
      externalOrderId: { kind: "string", minLength: 1 },
      itemsDelivery: {
        kind: "array",
        items: { kind: "ref", name: "CreateOrderWarehouseItemsDTO" },
      },
      destination: { kind: "ref", name: "CreateOrderDeliveryOptionDTO" },
      customer: { kind: "ref", name: "CustomerDTO" },
      packaging: { kind: "ref", name: "CreateOrderPackagingDTO" },
      paymentType: { kind: "ref", name: "DeliveryPaymentType" },
      draft: { kind: "boolean" },
      fake: { kind: "boolean" },
    },
    required: [
      "externalOrderId",
      "itemsDelivery",
      "destination",
      "customer",
      "packaging",
      "paymentType",
    ],
  },
  CreateOrderDeliveryOptionDTO: {
    kind: "object",
    properties: {
      pickupDelivery: { kind: "ref", name: "OrderPickupDeliveryDTO" },
      courierDelivery: { kind: "ref", name: "OrderCourierDeliveryDTO" },
    },
    required: [],
  },
  CreateOrderItemDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      count: { kind: "number", integer: true, minimum: 1, maximum: 1000 },
      price: { kind: "ref", name: "BasePriceDTO" },
    },
    required: ["offerId", "count"],
  },
  CreateOrderPackageType: { kind: "string", enum: ["WHITELABEL", "BRAND"] },
  CreateOrderPackagingDTO: {
    kind: "object",
    properties: {
      packageType: { kind: "ref", name: "CreateOrderPackageType" },
    },
    required: [],
  },
  CreateOrderRequest: {
    kind: "object",
    properties: { order: { kind: "ref", name: "CreateOrderDTO" } },
    required: ["order"],
  },
  CreateOrderResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "CreatedOrdersDTO" },
    },
    required: ["status"],
  },
  CreateOrderWarehouseItemsDTO: {
    kind: "object",
    properties: {
      warehouseId: { kind: "number", integer: true, minimum: 1 },
      items: {
        kind: "array",
        items: { kind: "ref", name: "CreateOrderItemDTO" },
      },
      deliveryDateInterval: { kind: "ref", name: "DeliveryDateIntervalDTO" },
      deliveryTimeInterval: { kind: "ref", name: "TimeIntervalDTO" },
    },
    required: ["warehouseId", "items", "deliveryDateInterval"],
  },
  CreatedOrderDTO: {
    kind: "object",
    properties: { id: { kind: "number", integer: true } },
    required: ["id"],
  },
  CreatedOrdersDTO: {
    kind: "object",
    properties: {
      orders: {
        kind: "array",
        items: { kind: "ref", name: "CreatedOrderDTO" },
      },
    },
    required: ["orders"],
  },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  CurrencyValueDTO: {
    kind: "object",
    properties: {
      value: { kind: "number" },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  CustomerDTO: {
    kind: "object",
    properties: {
      firstName: { kind: "string", minLength: 1, maxLength: 512 },
      lastName: { kind: "string", minLength: 1, maxLength: 512 },
      middleName: { kind: "string", minLength: 1, maxLength: 512 },
      phone: { kind: "string", minLength: 5, maxLength: 16 },
    },
    required: ["firstName", "lastName", "phone"],
  },
  DateDdMmYyyy: { kind: "string" },
  DateDdMmYyyyHhMmSs: { kind: "string" },
  DeliveryDateIntervalDTO: {
    kind: "object",
    properties: { fromDate: { kind: "string" }, toDate: { kind: "string" } },
    required: ["fromDate", "toDate"],
  },
  DeliveryIntervalsUpdateOptionDTO: {
    kind: "object",
    properties: {
      deliveryDateInterval: { kind: "ref", name: "DeliveryDateIntervalDTO" },
      deliveryTimeInterval: { kind: "ref", name: "TimeIntervalDTO" },
    },
    required: ["deliveryDateInterval", "deliveryTimeInterval"],
  },
  DeliveryIntervalsUpdateOptionsDTO: {
    kind: "object",
    properties: {
      availableDeliveryIntervals: {
        kind: "array",
        items: { kind: "ref", name: "DeliveryIntervalsUpdateOptionDTO" },
      },
    },
    required: ["availableDeliveryIntervals"],
  },
  DeliveryPaymentType: { kind: "string", enum: ["PREPAID"] },
  DeliveryPriceDTO: {
    kind: "object",
    properties: {
      payment: { kind: "ref", name: "CurrencyValueDTO" },
      subsidy: { kind: "ref", name: "CurrencyValueDTO" },
      vat: { kind: "ref", name: "OrderVatType" },
    },
    required: [],
  },
  DigitalGoodsDeliveryDetailsDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "DigitalGoodsDeliveryType" },
      steamLink: { kind: "string" },
    },
    required: ["type"],
  },
  DigitalGoodsDeliveryType: {
    kind: "string",
    enum: ["EMAIL", "ACTIVATION_CODE", "STEAM_GIFT", "CHAT"],
  },
  EmptyApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  EnrichedOrderBoxLayoutDTO: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "OrderBoxLayoutItemDTO" },
      },
      boxId: { kind: "number", integer: true },
    },
    required: ["items"],
  },
  ExternalOrderId: { kind: "string", minLength: 1 },
  FlippingPagerDTO: {
    kind: "object",
    properties: {
      total: { kind: "number", integer: true },
      from: { kind: "number", integer: true },
      to: { kind: "number", integer: true },
      currentPage: { kind: "number", integer: true },
      pagesCount: { kind: "number", integer: true },
      pageSize: { kind: "number", integer: true },
    },
    required: [],
  },
  GetBusinessOrdersRequest: {
    kind: "object",
    properties: {
      orderIds: {
        kind: "array",
        items: { kind: "number", integer: true },
        nullable: true,
      },
      externalOrderIds: {
        kind: "array",
        items: { kind: "ref", name: "ExternalOrderId" },
        nullable: true,
      },
      programTypes: {
        kind: "array",
        items: { kind: "ref", name: "SellingProgramType" },
        nullable: true,
      },
      campaignIds: {
        kind: "array",
        items: { kind: "ref", name: "CampaignId" },
        nullable: true,
      },
      statuses: {
        kind: "array",
        items: { kind: "ref", name: "OrderStatusType" },
        nullable: true,
      },
      substatuses: {
        kind: "array",
        items: { kind: "ref", name: "OrderSubstatusType" },
        nullable: true,
      },
      dates: { kind: "ref", name: "OrderDatesFilterDTO" },
      fake: { kind: "boolean" },
      waitingForCancellationApprove: { kind: "boolean" },
      sourcePlatforms: {
        kind: "array",
        items: { kind: "ref", name: "OrderSourcePlatformType" },
        nullable: true,
      },
    },
    required: [],
  },
  GetBusinessOrdersResponse: {
    kind: "object",
    properties: {
      orders: {
        kind: "array",
        items: { kind: "ref", name: "BusinessOrderDTO" },
      },
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
    },
    required: ["orders"],
  },
  GetOrderIdentifiersStatusDTO: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemValidationStatusDTO" },
      },
    },
    required: ["items"],
  },
  GetOrderIdentifiersStatusResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GetOrderIdentifiersStatusDTO" },
    },
    required: ["status"],
  },
  GetOrderResponse: {
    kind: "object",
    properties: { order: { kind: "ref", name: "OrderDTO" } },
    required: [],
  },
  GetOrderUpdateOptionsRequest: {
    kind: "object",
    properties: { id: { kind: "number", integer: true } },
    required: ["id"],
  },
  GetOrderUpdateOptionsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "OrderUpdateOptionsDTO" },
    },
    required: ["status"],
  },
  GetOrdersResponse: {
    kind: "object",
    properties: {
      pager: { kind: "ref", name: "FlippingPagerDTO" },
      orders: { kind: "array", items: { kind: "ref", name: "OrderDTO" } },
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
    },
    required: ["orders"],
  },
  GpsDTO: {
    kind: "object",
    properties: { latitude: { kind: "number" }, longitude: { kind: "number" } },
    required: ["latitude", "longitude"],
  },
  ItemPriceDTO: {
    kind: "object",
    properties: {
      payment: { kind: "ref", name: "CurrencyValueDTO" },
      subsidy: { kind: "ref", name: "CurrencyValueDTO" },
      cashback: { kind: "ref", name: "CurrencyValueDTO" },
      vat: { kind: "ref", name: "OrderVatType" },
    },
    required: [],
  },
  LogisticPointId: { kind: "number", integer: true, minimum: 1 },
  OperationDTO: {
    kind: "object",
    properties: {
      id: { kind: "ref", name: "OperationId" },
      type: { kind: "ref", name: "OperationType" },
    },
    required: ["id", "type"],
  },
  OperationId: { kind: "string", minLength: 1, maxLength: 1000 },
  OperationType: {
    kind: "string",
    enum: [
      "ORDER_RECIPIENT_UPDATE",
      "ORDER_DELIVERY_INTERVAL_UPDATE",
      "ORDER_STATUS_UPDATE",
      "RETURN_CANCELLATION",
    ],
  },
  OrderBoxLayoutDTO: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "OrderBoxLayoutItemDTO" },
      },
    },
    required: ["items"],
  },
  OrderBoxLayoutItemDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      fullCount: { kind: "number", integer: true, minimum: 1 },
      partialCount: { kind: "ref", name: "OrderBoxLayoutPartialCountDTO" },
      instances: {
        kind: "array",
        items: { kind: "ref", name: "BriefOrderItemInstanceDTO" },
        nullable: true,
      },
    },
    required: ["id"],
  },
  OrderBoxLayoutPartialCountDTO: {
    kind: "object",
    properties: {
      current: { kind: "number", integer: true, minimum: 1 },
      total: { kind: "number", integer: true, minimum: 2 },
    },
    required: ["current", "total"],
  },
  OrderBoxesLayoutDTO: {
    kind: "object",
    properties: {
      boxes: {
        kind: "array",
        items: { kind: "ref", name: "EnrichedOrderBoxLayoutDTO" },
      },
    },
    required: ["boxes"],
  },
  OrderBuyerBasicInfoDTO: {
    kind: "object",
    properties: {
      id: { kind: "string" },
      lastName: { kind: "string" },
      firstName: { kind: "string" },
      middleName: { kind: "string" },
      type: { kind: "ref", name: "OrderBuyerType" },
    },
    required: ["type"],
  },
  OrderBuyerDTO: {
    kind: "object",
    properties: {
      id: { kind: "string" },
      lastName: { kind: "string" },
      firstName: { kind: "string" },
      middleName: { kind: "string" },
      type: { kind: "ref", name: "OrderBuyerType" },
    },
    required: ["type"],
  },
  OrderBuyerType: { kind: "string", enum: ["PERSON", "BUSINESS"] },
  OrderCancellationReasonType: {
    kind: "string",
    enum: ["ORDER_DELIVERED", "ORDER_IN_DELIVERY"],
  },
  OrderCourierDTO: {
    kind: "object",
    properties: {
      fullName: { kind: "string" },
      phone: { kind: "string" },
      phoneExtension: { kind: "string" },
      vehicleNumber: { kind: "string" },
      vehicleDescription: { kind: "string" },
    },
    required: [],
  },
  OrderCourierDeliveryDTO: {
    kind: "object",
    properties: {
      address: { kind: "ref", name: "CourierDeliveryAddressDTO" },
      notes: { kind: "string", minLength: 1, maxLength: 3000 },
    },
    required: ["address"],
  },
  OrderDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      externalOrderId: { kind: "ref", name: "ExternalOrderId" },
      status: { kind: "ref", name: "OrderStatusType" },
      substatus: { kind: "ref", name: "OrderSubstatusType" },
      creationDate: { kind: "ref", name: "DateDdMmYyyyHhMmSs" },
      updatedAt: { kind: "ref", name: "DateDdMmYyyyHhMmSs" },
      currency: { kind: "ref", name: "CurrencyType" },
      itemsTotal: { kind: "number" },
      deliveryTotal: { kind: "number" },
      buyerItemsTotal: { kind: "number" },
      buyerTotal: { kind: "number" },
      buyerItemsTotalBeforeDiscount: { kind: "number" },
      buyerTotalBeforeDiscount: { kind: "number" },
      paymentType: { kind: "ref", name: "OrderPaymentType" },
      paymentMethod: { kind: "ref", name: "OrderPaymentMethodType" },
      fake: { kind: "boolean" },
      items: { kind: "array", items: { kind: "ref", name: "OrderItemDTO" } },
      subsidies: {
        kind: "array",
        items: { kind: "ref", name: "OrderSubsidyDTO" },
        nullable: true,
      },
      delivery: { kind: "ref", name: "OrderDeliveryDTO" },
      buyer: { kind: "ref", name: "OrderBuyerDTO" },
      notes: { kind: "string" },
      taxSystem: { kind: "ref", name: "OrderTaxSystemType" },
      cancelRequested: { kind: "boolean" },
      expiryDate: { kind: "ref", name: "DateDdMmYyyyHhMmSs" },
    },
    required: [
      "id",
      "status",
      "substatus",
      "creationDate",
      "currency",
      "itemsTotal",
      "deliveryTotal",
      "buyerItemsTotalBeforeDiscount",
      "paymentType",
      "paymentMethod",
      "fake",
      "items",
      "delivery",
      "buyer",
      "taxSystem",
    ],
  },
  OrderDatesFilterDTO: {
    kind: "object",
    properties: {
      creationDateFrom: { kind: "string" },
      creationDateTo: { kind: "string" },
      shipmentDateFrom: { kind: "string" },
      shipmentDateTo: { kind: "string" },
      updateDateFrom: { kind: "string" },
      updateDateTo: { kind: "string" },
    },
    required: [],
  },
  OrderDeliveryAddressDTO: {
    kind: "object",
    properties: {
      country: { kind: "string" },
      postcode: { kind: "string" },
      city: { kind: "string" },
      district: { kind: "string" },
      subway: { kind: "string" },
      street: { kind: "string" },
      house: { kind: "string" },
      estate: { kind: "string" },
      block: { kind: "string" },
      building: { kind: "string" },
      entrance: { kind: "string" },
      entryphone: { kind: "string" },
      floor: { kind: "string" },
      apartment: { kind: "string" },
      phone: { kind: "string" },
      recipient: { kind: "string" },
      gps: { kind: "ref", name: "GpsDTO" },
    },
    required: [],
  },
  OrderDeliveryDTO: {
    kind: "object",
    properties: {
      id: { kind: "string" },
      type: { kind: "ref", name: "OrderDeliveryType" },
      serviceName: { kind: "string" },
      price: { kind: "number" },
      deliveryPartnerType: { kind: "ref", name: "OrderDeliveryPartnerType" },
      courier: { kind: "ref", name: "OrderCourierDTO" },
      dates: { kind: "ref", name: "OrderDeliveryDatesDTO" },
      region: { kind: "ref", name: "RegionDTO" },
      address: { kind: "ref", name: "OrderDeliveryAddressDTO" },
      vat: { kind: "ref", name: "OrderVatType" },
      deliveryServiceId: { kind: "number", integer: true },
      liftType: { kind: "ref", name: "OrderLiftType" },
      liftPrice: { kind: "number" },
      outletCode: { kind: "string" },
      outletStorageLimitDate: { kind: "ref", name: "DateDdMmYyyy" },
      dispatchType: { kind: "ref", name: "OrderDeliveryDispatchType" },
      tracks: {
        kind: "array",
        items: { kind: "ref", name: "OrderTrackDTO" },
        nullable: true,
      },
      shipments: {
        kind: "array",
        items: { kind: "ref", name: "OrderShipmentDTO" },
        nullable: true,
      },
      estimated: { kind: "boolean" },
      eacType: { kind: "ref", name: "OrderDeliveryEacType" },
      eacCode: { kind: "string" },
      receiveCode: { kind: "string" },
    },
    required: [
      "type",
      "serviceName",
      "deliveryPartnerType",
      "dates",
      "deliveryServiceId",
    ],
  },
  OrderDeliveryDatesDTO: {
    kind: "object",
    properties: {
      fromDate: { kind: "ref", name: "DateDdMmYyyy" },
      toDate: { kind: "ref", name: "DateDdMmYyyy" },
      fromTime: { kind: "string" },
      toTime: { kind: "string" },
      realDeliveryDate: { kind: "ref", name: "DateDdMmYyyy" },
    },
    required: ["fromDate"],
  },
  OrderDeliveryDispatchType: {
    kind: "string",
    enum: ["UNKNOWN", "BUYER", "MARKET_BRANDED_OUTLET", "SHOP_OUTLET"],
  },
  OrderDeliveryEacType: {
    kind: "string",
    enum: [
      "MERCHANT_TO_COURIER",
      "COURIER_TO_MERCHANT",
      "CHECKING_BY_MERCHANT",
    ],
  },
  OrderDeliveryPartnerType: {
    kind: "string",
    enum: ["SHOP", "YANDEX_MARKET", "UNKNOWN"],
  },
  OrderDeliveryType: {
    kind: "string",
    enum: ["DELIVERY", "PICKUP", "POST", "DIGITAL", "UNKNOWN"],
  },
  OrderDigitalItemDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      codes: {
        kind: "array",
        items: { kind: "string", maxLength: 256 },
        nullable: true,
      },
      slip: { kind: "string", maxLength: 10000 },
      activate_till: { kind: "string" },
    },
    required: ["id", "slip", "activate_till"],
  },
  OrderItemDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      offerId: { kind: "ref", name: "ShopSku" },
      offerName: { kind: "string" },
      price: { kind: "number" },
      buyerPrice: { kind: "number" },
      buyerPriceBeforeDiscount: { kind: "number" },
      priceBeforeDiscount: { kind: "number" },
      count: { kind: "number", integer: true },
      vat: { kind: "ref", name: "OrderVatType" },
      shopSku: { kind: "ref", name: "ShopSku" },
      subsidy: { kind: "number" },
      partnerWarehouseId: { kind: "string" },
      promos: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemPromoDTO" },
        nullable: true,
      },
      instances: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemInstanceDTO" },
        nullable: true,
      },
      details: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemDetailDTO" },
        nullable: true,
      },
      subsidies: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemSubsidyDTO" },
        nullable: true,
      },
      requiredInstanceTypes: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemInstanceType" },
        nullable: true,
      },
      tags: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemTagType" },
        nullable: true,
      },
    },
    required: [
      "id",
      "offerId",
      "offerName",
      "price",
      "buyerPrice",
      "buyerPriceBeforeDiscount",
      "count",
    ],
  },
  OrderItemDetailDTO: {
    kind: "object",
    properties: {
      itemCount: { kind: "number", integer: true },
      itemStatus: { kind: "ref", name: "OrderItemStatusType" },
      updateDate: { kind: "ref", name: "DateDdMmYyyy" },
    },
    required: ["itemCount", "itemStatus", "updateDate"],
  },
  OrderItemInstanceDTO: {
    kind: "object",
    properties: {
      cis: { kind: "string" },
      cisFull: { kind: "string" },
      uin: { kind: "string" },
      rnpt: { kind: "string" },
      gtd: { kind: "string" },
      countryCode: { kind: "ref", name: "CountryCode" },
    },
    required: [],
  },
  OrderItemInstanceModificationDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      instances: {
        kind: "array",
        items: { kind: "ref", name: "BriefOrderItemInstanceDTO" },
      },
    },
    required: ["id", "instances"],
  },
  OrderItemInstanceType: {
    kind: "string",
    enum: ["CIS", "CIS_OPTIONAL", "UIN", "RNPT", "GTD"],
  },
  OrderItemModificationDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      count: { kind: "number", integer: true, minimum: 0 },
      instances: {
        kind: "array",
        items: { kind: "ref", name: "BriefOrderItemInstanceDTO" },
        nullable: true,
      },
    },
    required: ["id", "count"],
  },
  OrderItemPromoDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "OrderPromoType" },
      discount: { kind: "number" },
      subsidy: { kind: "number" },
      shopPromoId: { kind: "string" },
      marketPromoId: { kind: "string" },
    },
    required: ["type", "subsidy"],
  },
  OrderItemStatusType: { kind: "string", enum: ["REJECTED", "RETURNED"] },
  OrderItemSubsidyDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "OrderItemSubsidyType" },
      amount: { kind: "number" },
    },
    required: ["type", "amount"],
  },
  OrderItemSubsidyType: {
    kind: "string",
    enum: ["YANDEX_CASHBACK", "SUBSIDY"],
  },
  OrderItemTagType: { kind: "string", enum: ["ULTIMA", "SAFE_TAG"] },
  OrderItemUnitStatusDTO: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "OrderItemUnitStatusType" },
      count: { kind: "number", integer: true },
    },
    required: ["status", "count"],
  },
  OrderItemUnitStatusType: {
    kind: "string",
    enum: [
      "CREATED",
      "SHIPPED",
      "CANCELLED",
      "DELIVERED_TO_BUYER",
      "LOST",
      "REJECTED",
      "RETURNED",
    ],
  },
  OrderItemValidationStatusDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      uin: {
        kind: "array",
        items: { kind: "ref", name: "UinDTO" },
        nullable: true,
      },
      cis: {
        kind: "array",
        items: { kind: "ref", name: "CisDTO" },
        nullable: true,
      },
    },
    required: ["id"],
  },
  OrderItemsModificationRequestReasonType: {
    kind: "string",
    enum: ["PARTNER_REQUESTED_REMOVE", "USER_REQUESTED_REMOVE"],
  },
  OrderItemsModificationResultDTO: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "BriefOrderItemDTO" },
      },
    },
    required: ["items"],
  },
  OrderLiftType: {
    kind: "string",
    enum: [
      "NOT_NEEDED",
      "MANUAL",
      "ELEVATOR",
      "CARGO_ELEVATOR",
      "FREE",
      "UNKNOWN",
    ],
  },
  OrderParcelBoxDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      fulfilmentId: { kind: "string" },
    },
    required: ["id", "fulfilmentId"],
  },
  OrderPaymentMethodType: {
    kind: "string",
    enum: [
      "CASH_ON_DELIVERY",
      "CARD_ON_DELIVERY",
      "BOUND_CARD_ON_DELIVERY",
      "BNPL_BANK_ON_DELIVERY",
      "BNPL_ON_DELIVERY",
      "YANDEX",
      "APPLE_PAY",
      "EXTERNAL_CERTIFICATE",
      "CREDIT",
      "GOOGLE_PAY",
      "TINKOFF_CREDIT",
      "SBP",
      "TINKOFF_INSTALLMENTS",
      "B2B_ACCOUNT_PREPAYMENT",
      "B2B_ACCOUNT_POSTPAYMENT",
      "MICROCREDIT",
      "BNPL_TBYB",
      "BNPL_TBC",
      "DIGITAL_RUBLE",
      "UNKNOWN",
    ],
  },
  OrderPaymentType: {
    kind: "string",
    enum: ["PREPAID", "POSTPAID", "UNKNOWN"],
  },
  OrderPickupDeliveryDTO: {
    kind: "object",
    properties: { logisticPointId: { kind: "ref", name: "LogisticPointId" } },
    required: ["logisticPointId"],
  },
  OrderPriceDTO: {
    kind: "object",
    properties: {
      payment: { kind: "ref", name: "CurrencyValueDTO" },
      subsidy: { kind: "ref", name: "CurrencyValueDTO" },
      cashback: { kind: "ref", name: "CurrencyValueDTO" },
      delivery: { kind: "ref", name: "DeliveryPriceDTO" },
    },
    required: [],
  },
  OrderPromoType: {
    kind: "string",
    enum: [
      "DIRECT_DISCOUNT",
      "BLUE_SET",
      "BLUE_FLASH",
      "GENERIC_BUNDLE",
      "MARKET_COUPON",
      "MARKET_PROMOCODE",
      "MARKET_BLUE",
      "MARKET_COIN",
      "PRICE_DROP_AS_YOU_SHOP",
      "SECRET_SALE",
      "CHEAPEST_AS_GIFT",
      "CASHBACK",
      "SPREAD_DISCOUNT_COUNT",
      "SPREAD_DISCOUNT_RECEIPT",
      "DISCOUNT_BY_PAYMENT_TYPE",
      "PERCENT_DISCOUNT",
      "DCO_EXTRA_DISCOUNT",
      "UNKNOWN",
    ],
  },
  OrderShipmentDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      shipmentDate: { kind: "ref", name: "DateDdMmYyyy" },
      shipmentTime: { kind: "string" },
      tracks: {
        kind: "array",
        items: { kind: "ref", name: "OrderTrackDTO" },
        nullable: true,
      },
      boxes: {
        kind: "array",
        items: { kind: "ref", name: "OrderParcelBoxDTO" },
        nullable: true,
      },
    },
    required: [],
  },
  OrderSourcePlatformType: {
    kind: "string",
    enum: ["MARKET", "OZON", "WILDBERRIES", "OTHER"],
  },
  OrderStateDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      status: { kind: "ref", name: "OrderStatusType" },
      substatus: { kind: "ref", name: "OrderSubstatusType" },
    },
    required: ["id", "status"],
  },
  OrderStatusChangeDTO: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "OrderStatusType" },
      substatus: { kind: "ref", name: "OrderSubstatusType" },
      delivery: { kind: "ref", name: "OrderStatusChangeDeliveryDTO" },
    },
    required: ["status"],
  },
  OrderStatusChangeDeliveryDTO: {
    kind: "object",
    properties: {
      dates: { kind: "ref", name: "OrderStatusChangeDeliveryDatesDTO" },
    },
    required: [],
  },
  OrderStatusChangeDeliveryDatesDTO: {
    kind: "object",
    properties: { realDeliveryDate: { kind: "string" } },
    required: [],
  },
  OrderStatusType: {
    kind: "string",
    enum: [
      "PLACING",
      "RESERVED",
      "UNPAID",
      "PROCESSING",
      "DELIVERY",
      "PICKUP",
      "DELIVERED",
      "CANCELLED",
      "PENDING",
      "PARTIALLY_RETURNED",
      "RETURNED",
      "UNKNOWN",
    ],
  },
  OrderSubsidyDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "OrderSubsidyType" },
      amount: { kind: "number" },
    },
    required: ["type", "amount"],
  },
  OrderSubsidyType: {
    kind: "string",
    enum: ["YANDEX_CASHBACK", "SUBSIDY", "DELIVERY"],
  },
  OrderSubstatusType: {
    kind: "string",
    enum: [
      "RESERVATION_EXPIRED",
      "USER_NOT_PAID",
      "USER_UNREACHABLE",
      "USER_CHANGED_MIND",
      "USER_REFUSED_DELIVERY",
      "USER_REFUSED_PRODUCT",
      "SHOP_FAILED",
      "USER_REFUSED_QUALITY",
      "REPLACING_ORDER",
      "PROCESSING_EXPIRED",
      "PENDING_EXPIRED",
      "SHOP_PENDING_CANCELLED",
      "PENDING_CANCELLED",
      "USER_FRAUD",
      "RESERVATION_FAILED",
      "USER_PLACED_OTHER_ORDER",
      "USER_BOUGHT_CHEAPER",
      "MISSING_ITEM",
      "BROKEN_ITEM",
      "WRONG_ITEM",
      "PICKUP_EXPIRED",
      "DELIVERY_PROBLEMS",
      "LATE_CONTACT",
      "CUSTOM",
      "DELIVERY_SERVICE_FAILED",
      "WAREHOUSE_FAILED_TO_SHIP",
      "DELIVERY_SERVICE_UNDELIVERED",
      "PREORDER",
      "AWAIT_CONFIRMATION",
      "STARTED",
      "PACKAGING",
      "READY_TO_SHIP",
      "SHIPPED",
      "ASYNC_PROCESSING",
      "WAITING_USER_INPUT",
      "WAITING_BANK_DECISION",
      "BANK_REJECT_CREDIT_OFFER",
      "CUSTOMER_REJECT_CREDIT_OFFER",
      "CREDIT_OFFER_FAILED",
      "AWAIT_DELIVERY_DATES_CONFIRMATION",
      "SERVICE_FAULT",
      "DELIVERY_SERVICE_RECEIVED",
      "USER_RECEIVED",
      "WAITING_FOR_STOCKS",
      "AS_PART_OF_MULTI_ORDER",
      "READY_FOR_LAST_MILE",
      "LAST_MILE_STARTED",
      "ANTIFRAUD",
      "DELIVERY_USER_NOT_RECEIVED",
      "DELIVERY_SERVICE_DELIVERED",
      "DELIVERED_USER_NOT_RECEIVED",
      "USER_WANTED_ANOTHER_PAYMENT_METHOD",
      "USER_RECEIVED_TECHNICAL_ERROR",
      "USER_FORGOT_TO_USE_BONUS",
      "DELIVERY_SERVICE_NOT_RECEIVED",
      "DELIVERY_SERVICE_LOST",
      "SHIPPED_TO_WRONG_DELIVERY_SERVICE",
      "DELIVERED_USER_RECEIVED",
      "WAITING_TINKOFF_DECISION",
      "COURIER_SEARCH",
      "COURIER_FOUND",
      "COURIER_IN_TRANSIT_TO_SENDER",
      "COURIER_ARRIVED_TO_SENDER",
      "COURIER_RECEIVED",
      "COURIER_NOT_FOUND",
      "COURIER_NOT_DELIVER_ORDER",
      "COURIER_RETURNS_ORDER",
      "COURIER_RETURNED_ORDER",
      "WAITING_USER_DELIVERY_INPUT",
      "PICKUP_SERVICE_RECEIVED",
      "PICKUP_USER_RECEIVED",
      "CANCELLED_COURIER_NOT_FOUND",
      "COURIER_NOT_COME_FOR_ORDER",
      "DELIVERY_NOT_MANAGED_REGION",
      "INCOMPLETE_CONTACT_INFORMATION",
      "INCOMPLETE_MULTI_ORDER",
      "INAPPROPRIATE_WEIGHT_SIZE",
      "TECHNICAL_ERROR",
      "SORTING_CENTER_LOST",
      "COURIER_SEARCH_NOT_STARTED",
      "LOST",
      "AWAIT_PAYMENT",
      "AWAIT_LAVKA_RESERVATION",
      "USER_WANTS_TO_CHANGE_ADDRESS",
      "FULL_NOT_RANSOM",
      "PRESCRIPTION_MISMATCH",
      "DROPOFF_LOST",
      "DROPOFF_CLOSED",
      "DELIVERY_TO_STORE_STARTED",
      "USER_WANTS_TO_CHANGE_DELIVERY_DATE",
      "WRONG_ITEM_DELIVERED",
      "DAMAGED_BOX",
      "AWAIT_DELIVERY_DATES",
      "LAST_MILE_COURIER_SEARCH",
      "PICKUP_POINT_CLOSED",
      "LEGAL_INFO_CHANGED",
      "USER_HAS_NO_TIME_TO_PICKUP_ORDER",
      "DELIVERY_CUSTOMS_ARRIVED",
      "DELIVERY_CUSTOMS_CLEARED",
      "FIRST_MILE_DELIVERY_SERVICE_RECEIVED",
      "AWAIT_AUTO_DELIVERY_DATES",
      "AWAIT_USER_PERSONAL_DATA",
      "NO_PERSONAL_DATA_EXPIRED",
      "CUSTOMS_PROBLEMS",
      "AWAIT_CASHIER",
      "WAITING_POSTPAID_BUDGET_RESERVATION",
      "AWAIT_SERVICEABLE_CONFIRMATION",
      "POSTPAID_BUDGET_RESERVATION_FAILED",
      "AWAIT_CUSTOM_PRICE_CONFIRMATION",
      "READY_FOR_PICKUP",
      "TOO_MANY_DELIVERY_DATE_CHANGES",
      "TOO_LONG_DELIVERY",
      "DEFERRED_PAYMENT",
      "POSTPAID_FAILED",
      "INCORRECT_PERSONAL_DATA",
      "CUSTOMS_FAILED_MARKET",
      "CUSTOMS_FAILED_USER_COMMERCIAL_ITEMS",
      "CUSTOMS_FAILED_USER_DUTY_NOT_PAID",
      "CUSTOMS_FAILED_USER_INVALID_PERSONAL_DATA",
      "CUSTOMS_FAILED_USER_ADDITIONAL_DATA_NOT_PROVIDED",
      "AWAIT_PAYMENT_AFTER_DELIVERY",
      "AWAIT_USER_STEAM_FAST_URL",
      "USER_IDENTIFICATION_MISMATCH",
      "PURCHASE_GROUP_THRESHOLD_NOT_REACHED_CANCELLED",
      "UNKNOWN",
    ],
  },
  OrderTaxSystemType: {
    kind: "string",
    enum: [
      "OSN",
      "USN",
      "USN_MINUS_COST",
      "ENVD",
      "ECHN",
      "PSN",
      "NPD",
      "AUSN",
      "AUSN_MINUS_COST",
      "UNKNOWN_VALUE",
    ],
  },
  OrderTrackDTO: {
    kind: "object",
    properties: {
      trackCode: { kind: "string" },
      deliveryServiceId: { kind: "number", integer: true },
    },
    required: ["deliveryServiceId"],
  },
  OrderUpdateOptionsDTO: {
    kind: "object",
    properties: {
      deliveryIntervals: {
        kind: "ref",
        name: "DeliveryIntervalsUpdateOptionsDTO",
      },
    },
    required: ["deliveryIntervals"],
  },
  OrderUpdateStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  OrderVatType: {
    kind: "string",
    enum: [
      "NO_VAT",
      "VAT_0",
      "VAT_10",
      "VAT_10_110",
      "VAT_20",
      "VAT_20_120",
      "VAT_18",
      "VAT_18_118",
      "VAT_12",
      "VAT_05",
      "VAT_07",
      "VAT_22",
      "UNKNOWN_VALUE",
    ],
  },
  PackagingForwardScrollingPagerDTO: {
    kind: "object",
    properties: { nextPageToken: { kind: "string" } },
    required: [],
  },
  ParcelBoxDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      fulfilmentId: { kind: "string" },
    },
    required: [],
  },
  ParcelBoxRequestDTO: {
    kind: "object",
    properties: { fulfilmentId: { kind: "string" } },
    required: [],
  },
  ParcelRequestDTO: {
    kind: "object",
    properties: {
      boxes: {
        kind: "array",
        items: { kind: "ref", name: "ParcelBoxRequestDTO" },
      },
    },
    required: ["boxes"],
  },
  ProvideOrderDigitalCodesRequest: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "OrderDigitalItemDTO" },
      },
    },
    required: ["items"],
  },
  ProvideOrderItemIdentifiersRequest: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemInstanceModificationDTO" },
      },
    },
    required: ["items"],
  },
  ProvideOrderItemIdentifiersResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "OrderItemsModificationResultDTO" },
    },
    required: ["status"],
  },
  RegionDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      name: { kind: "string" },
      type: { kind: "ref", name: "RegionType" },
      parent: { kind: "ref", name: "RegionDTO" },
    },
    required: ["id", "name", "type"],
  },
  RegionType: {
    kind: "string",
    enum: [
      "OTHER",
      "CONTINENT",
      "REGION",
      "COUNTRY",
      "COUNTRY_DISTRICT",
      "REPUBLIC",
      "CITY",
      "VILLAGE",
      "CITY_DISTRICT",
      "SUBWAY_STATION",
      "REPUBLIC_AREA",
    ],
  },
  SellingProgramType: {
    kind: "string",
    enum: ["FBY", "FBS", "DBS", "EXPRESS", "LAAS"],
  },
  SetOrderBoxLayoutRequest: {
    kind: "object",
    properties: {
      boxes: {
        kind: "array",
        items: { kind: "ref", name: "OrderBoxLayoutDTO" },
      },
      allowRemove: { kind: "boolean" },
    },
    required: ["boxes"],
  },
  SetOrderBoxLayoutResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "OrderBoxesLayoutDTO" },
    },
    required: ["status"],
  },
  SetOrderShipmentBoxesRequest: {
    kind: "object",
    properties: {
      boxes: {
        kind: "array",
        items: { kind: "ref", name: "ParcelBoxRequestDTO" },
      },
    },
    required: ["boxes"],
  },
  SetOrderShipmentBoxesResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "ShipmentBoxesDTO" },
    },
    required: ["status"],
  },
  ShipmentBoxesDTO: {
    kind: "object",
    properties: {
      boxes: { kind: "array", items: { kind: "ref", name: "ParcelBoxDTO" } },
    },
    required: ["boxes"],
  },
  ShopSku: { kind: "string", minLength: 1, maxLength: 255 },
  TimeIntervalDTO: {
    kind: "object",
    properties: { fromTime: { kind: "string" }, toTime: { kind: "string" } },
    required: ["fromTime", "toTime"],
  },
  UinDTO: {
    kind: "object",
    properties: {
      value: { kind: "string" },
      status: { kind: "ref", name: "UinStatusType" },
      substatus: { kind: "ref", name: "UinSubstatusType" },
    },
    required: ["value", "status"],
  },
  UinStatusType: {
    kind: "string",
    enum: ["OK", "IN_PROGRESS", "FAILED", "NOT_ON_VALIDATION"],
  },
  UinSubstatusType: {
    kind: "string",
    enum: ["UIN_MERCHANT_MISMATCH", "UIN_MERCHANT_UNREGISTERED", "UIN_NO_DATA"],
  },
  UpdateExternalOrderIdRequest: {
    kind: "object",
    properties: { externalOrderId: { kind: "string", minLength: 1 } },
    required: ["externalOrderId"],
  },
  UpdateOrderDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      deliveryInterval: {
        kind: "ref",
        name: "DeliveryIntervalsUpdateOptionDTO",
      },
      customer: { kind: "ref", name: "CustomerDTO" },
    },
    required: ["id"],
  },
  UpdateOrderItemRequest: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "OrderItemModificationDTO" },
      },
      reason: { kind: "ref", name: "OrderItemsModificationRequestReasonType" },
    },
    required: ["items"],
  },
  UpdateOrderRequest: {
    kind: "object",
    properties: { order: { kind: "ref", name: "UpdateOrderDTO" } },
    required: ["order"],
  },
  UpdateOrderResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "UpdateOrderResultDTO" },
    },
    required: ["status"],
  },
  UpdateOrderResultDTO: {
    kind: "object",
    properties: {
      operations: {
        kind: "array",
        items: { kind: "ref", name: "OperationDTO" },
      },
    },
    required: ["operations"],
  },
  UpdateOrderStatusDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      status: { kind: "ref", name: "OrderStatusType" },
      substatus: { kind: "ref", name: "OrderSubstatusType" },
      updateStatus: { kind: "ref", name: "OrderUpdateStatusType" },
      errorDetails: { kind: "string" },
      operation: { kind: "ref", name: "OperationDTO" },
    },
    required: [],
  },
  UpdateOrderStatusRequest: {
    kind: "object",
    properties: { order: { kind: "ref", name: "OrderStatusChangeDTO" } },
    required: ["order"],
  },
  UpdateOrderStatusResponse: {
    kind: "object",
    properties: {
      order: { kind: "ref", name: "OrderDTO" },
      operation: { kind: "ref", name: "OperationDTO" },
    },
    required: [],
  },
  UpdateOrderStatusesDTO: {
    kind: "object",
    properties: {
      orders: {
        kind: "array",
        items: { kind: "ref", name: "UpdateOrderStatusDTO" },
      },
    },
    required: ["orders"],
  },
  UpdateOrderStatusesRequest: {
    kind: "object",
    properties: {
      orders: { kind: "array", items: { kind: "ref", name: "OrderStateDTO" } },
    },
    required: ["orders"],
  },
  UpdateOrderStatusesResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "UpdateOrderStatusesDTO" },
    },
    required: ["status"],
  },
};
