// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const outletsComponents: YmSchemaComponents = {
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorCodeType: {
    kind: "string",
    enum: [
      "INVALID_FEED_ID",
      "INVALID_WAREHOUSE_ID",
      "GROUPED_WAREHOUSE",
      "DUPLICATE_OFFER",
      "INVALID_TTL",
      "INVALID_COMMENT",
      "LIMIT_EXCEEDED",
      "NON_POSITIVE_LIMIT",
      "REQUEST_LIMIT_EXCEEDED",
      "INVALID_OFFER_ID",
      "MISSING_OFFER_ID",
      "MISSING_OFFER",
      "INVALID_SHOP_SKU",
      "AMBIGUOUS_OFFER",
      "OFFER_NOT_FOUND",
      "MODEL_NOT_FOUND",
      "CATEGORY_NOT_FOUND",
      "NO_REQUIRED_FIELDS",
      "FORBIDDEN_FIELD_DEFINITION",
      "PROBLEMS_IN_OTHER_OFFERS",
      "AMBIGUOUS_FIELD_DEFINITION",
      "INVALID_OUTLET_INFO",
      "DUPLICATE_OUTLET_CODE",
      "UNKNOWN_REGION",
      "WRONG_REGION",
      "NOT_SPECIFIED",
      "INVALID_PHONE_FORMAT",
      "INVALID_TIME_FORMAT",
      "COULD_NOT_FIND_COORDS",
      "WRONG_OUTLET_GPS_COORDINATES",
      "ITEM_NOT_FOUND",
      "INVALID_ITEM",
      "ITEM_DUPLICATE",
      "ITEM_SHIPPED",
      "ITEMS_ADDITION_NOT_SUPPORTED",
      "CANNOT_REMOVE_LAST_ITEM",
      "OTHER_REMOVE_ITEM_ERROR",
      "TRACK_CODE_ALREADY_USED",
      "TOO_MANY_CISES_FOR_ITEM",
      "TOO_FEW_CISES_FOR_ITEM",
      "INVALID_CIS",
      "DUPLICATE_CIS",
      "TOO_MANY_UINS_FOR_ITEM",
      "TOO_FEW_UINS_FOR_ITEM",
      "INVALID_UIN",
      "UIN_VALIDATION_IN_PROGRESS_ERROR",
      "CIS_VALIDATION_IN_PROGRESS_ERROR",
      "INVALID_RNPT",
      "INVALID_GTD",
      "INVALID_COUNTRY_CODE",
      "COUNTRY_CODE_AND_GTD_ARE_REQUIRED_VALIDATION_ERROR",
      "DUPLICATE_UIN",
      "DELETED_ITEMS_EXCEEDS_THRESHOLD",
      "PROMO_PROHIBITS_DELETE",
      "PAYMENT_PROHIBITS_DELETE",
      "CANCELLATION_REQUESTED",
      "ORDER_IN_TERMINAL_STATE",
      "EDIT_COUNT_EXCEEDED",
      "DAYS_COUNT_EXCEEDED",
      "SAME_DELIVERY_DATES",
      "INCORRECT_INN",
      "BAD_REQUEST",
      "UNSUPPORTED_MEDIA_TYPE",
      "FORBIDDEN",
      "NOT_FOUND",
      "LOCKED",
      "CONSTRAINT_VIOLATION",
      "DUPLICATE_MARKET_SKU",
      "INVALID_MARKET_SKU",
      "INVALID_MAPPING",
      "MISSING_MAPPING",
      "UNKNOWN_PARAMETER",
      "INTERNAL_ERROR",
      "MISSING_PARAM",
      "DUPLICATE_SHOP_SKU",
      "INVALID_CURRENCY",
      "INVALID_PAYMENT_SETTINGS",
      "OTHER",
      "INVALID_CATEGORY",
      "INVALID_QUERY_PARAMETER",
      "CAMPAIGN_NOT_FOUND",
      "PARTNER_NOT_FOUND",
      "BUSINESS_NOT_FOUND",
      "CAMPAIGN_TYPE_NOT_SUPPORTED",
      "BAD_OFFERS",
      "ALREADY_CONFIRMED",
      "CUTOFF_NOT_REACHED",
      "NO_ORDERS",
      "BAD_ORDERS",
      "NO_BOXES",
      "INVALID_ORDER_BEFORE",
      "STATUS_NOT_ALLOWED",
      "SUBSTATUS_NOT_ALLOWED",
      "USER_UNREACHABLE_NOT_ALLOWED",
      "ACTION_FORBIDDEN",
      "CANT_DELIVER_ORDER_TO_ADDRESS",
      "PICKUP_EXPIRED_CANCELLATION_FORBIDDEN",
      "INVALID_ORDER_STATUS",
      "CODE_NEED_BE_REFRESHED",
      "CODE_ALREADY_ACCEPTED",
      "NO_EMAIL",
      "PROMO_ENDED",
      "PROMO_ENTRY_DEADLINE_EXCEEDED",
      "PROMO_MECHANICS_NOT_SUPPORTED",
      "PROMO_SINGLE_OFFER_TASK_LIMIT_EXCEEDED",
      "SUPPLY_REQUEST_NOT_FOUND",
      "DOCUMENT_NOT_FOUND",
      "EXTERNAL_ORDER_ID_UPDATE_ERROR",
      "DECLINE_REASON_ARE_REQUIRED_ERROR",
      "CONTRACT_NOT_FOUND",
      "CONTRACT_WITH_AGENCY",
      "NOT_ENOUGH_STOCK",
      "INVALID_DELIVERY_OPTION",
      "ORDER_ALREADY_EXISTS",
      "ORDER_MODIFICATION_NOT_ALLOWED",
      "DELIVERY_TAX_INFO_NO_DBS_PARTNER",
      "DELIVERY_TAX_INFO_INCORRECT_ORDER_STATUS",
      "DELIVERY_TAX_INFO_TAX_SYSTEM_IS_NOT_SUPPORTED",
      "DELIVERY_TAX_INFO_INCORRECT_DELIVERY_SERVICE",
      "DELIVERY_TAX_INFO_INCORRECT_REQUEST",
      "RETURN_ALREADY_EXISTS",
      "INVALID_RETURN_OFFERS",
      "PHOTO_UPLOAD_FAILED",
      "INVALID_DELIVERY_TYPE",
      "INVALID_RETURN_REASON",
      "INVALID_ITEM_DIMENSIONS",
      "API_DISABLED",
      "RESTRICTED_BY_MARKETPLACE_REGION",
      "NO_ACCESS_BY_DEPRECATION_POLICY",
      "ORDER_EDIT_ERROR",
      "ADVERTISER_STATUS_MISMATCH",
      "RESTRICTED_FOR_ADVERTISER",
      "SUBSCRIPTION_REQUIRED",
      "CIS_HANDLE_MODE_RESTRICTION",
    ],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiTypedClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiTypedErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiTypedErrorDTO: {
    kind: "object",
    properties: {
      code: { kind: "ref", name: "ApiErrorCodeType" },
      message: { kind: "string" },
    },
    required: ["code"],
  },
  ApiTypedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiTypedErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiTypedForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiTypedErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiTypedLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiTypedErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiTypedNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiTypedErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiTypedServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiTypedErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiTypedUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiTypedErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ChangeOutletRequest: {
    kind: "object",
    properties: {
      name: { kind: "string" },
      type: { kind: "ref", name: "OutletType" },
      coords: { kind: "string" },
      isMain: { kind: "boolean" },
      shopOutletCode: { kind: "string" },
      visibility: { kind: "ref", name: "OutletVisibilityType" },
      address: { kind: "ref", name: "OutletAddressDTO" },
      phones: { kind: "array", items: { kind: "string", minLength: 1 } },
      workingSchedule: { kind: "ref", name: "OutletWorkingScheduleDTO" },
      deliveryRules: {
        kind: "array",
        items: { kind: "ref", name: "OutletDeliveryRuleDTO" },
        nullable: true,
      },
      storagePeriod: { kind: "number", integer: true },
    },
    required: ["name", "type", "address", "phones", "workingSchedule"],
  },
  CreateOutletResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "OutletResponseDTO" },
    },
    required: ["status"],
  },
  DayOfWeekType: {
    kind: "string",
    enum: [
      "MONDAY",
      "TUESDAY",
      "WEDNESDAY",
      "THURSDAY",
      "FRIDAY",
      "SATURDAY",
      "SUNDAY",
    ],
  },
  EmptyApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  FullOutletDTO: {
    kind: "object",
    properties: {
      name: { kind: "string" },
      type: { kind: "ref", name: "OutletType" },
      coords: { kind: "string" },
      isMain: { kind: "boolean" },
      shopOutletCode: { kind: "string" },
      visibility: { kind: "ref", name: "OutletVisibilityType" },
      address: { kind: "ref", name: "OutletAddressDTO" },
      phones: { kind: "array", items: { kind: "string", minLength: 1 } },
      workingSchedule: { kind: "ref", name: "OutletWorkingScheduleDTO" },
      deliveryRules: {
        kind: "array",
        items: { kind: "ref", name: "OutletDeliveryRuleDTO" },
        nullable: true,
      },
      storagePeriod: { kind: "number", integer: true },
      id: { kind: "number", integer: true },
      status: { kind: "ref", name: "OutletStatusType" },
      region: { kind: "ref", name: "RegionDTO" },
      shopOutletId: { kind: "string" },
      workingTime: { kind: "string" },
      moderationReason: { kind: "string" },
    },
    required: ["name", "type", "address", "phones", "workingSchedule"],
  },
  GetOutletResponse: {
    kind: "object",
    properties: { outlet: { kind: "ref", name: "FullOutletDTO" } },
    required: [],
  },
  GetOutletsResponse: {
    kind: "object",
    properties: {
      outlets: { kind: "array", items: { kind: "ref", name: "FullOutletDTO" } },
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
    },
    required: ["outlets"],
  },
  OutletAddressDTO: {
    kind: "object",
    properties: {
      regionId: { kind: "number", integer: true },
      street: { kind: "string", maxLength: 512 },
      number: { kind: "string", maxLength: 256 },
      building: { kind: "string", maxLength: 16 },
      estate: { kind: "string", maxLength: 16 },
      block: { kind: "string", maxLength: 16 },
      additional: { kind: "string" },
      km: { kind: "number", integer: true },
      city: { kind: "string", maxLength: 200 },
    },
    required: ["regionId"],
  },
  OutletDTO: {
    kind: "object",
    properties: {
      name: { kind: "string" },
      type: { kind: "ref", name: "OutletType" },
      coords: { kind: "string" },
      isMain: { kind: "boolean" },
      shopOutletCode: { kind: "string" },
      visibility: { kind: "ref", name: "OutletVisibilityType" },
      address: { kind: "ref", name: "OutletAddressDTO" },
      phones: { kind: "array", items: { kind: "string", minLength: 1 } },
      workingSchedule: { kind: "ref", name: "OutletWorkingScheduleDTO" },
      deliveryRules: {
        kind: "array",
        items: { kind: "ref", name: "OutletDeliveryRuleDTO" },
        nullable: true,
      },
      storagePeriod: { kind: "number", integer: true },
    },
    required: ["name", "type", "address", "phones", "workingSchedule"],
  },
  OutletDeliveryRuleDTO: {
    kind: "object",
    properties: {
      minDeliveryDays: {
        kind: "number",
        integer: true,
        minimum: 0,
        maximum: 60,
      },
      maxDeliveryDays: {
        kind: "number",
        integer: true,
        minimum: 0,
        maximum: 60,
      },
      deliveryServiceId: { kind: "number", integer: true, minimum: 1 },
      orderBefore: { kind: "number", integer: true, minimum: 0, maximum: 24 },
      priceFreePickup: { kind: "number" },
      unspecifiedDeliveryInterval: { kind: "boolean" },
    },
    required: [],
  },
  OutletResponseDTO: {
    kind: "object",
    properties: { id: { kind: "number", integer: true } },
    required: [],
  },
  OutletStatusType: {
    kind: "string",
    enum: ["AT_MODERATION", "FAILED", "MODERATED", "NONMODERATED", "UNKNOWN"],
  },
  OutletType: {
    kind: "string",
    enum: ["DEPOT", "MIXED", "RETAIL", "NOT_DEFINED"],
  },
  OutletVisibilityType: {
    kind: "string",
    enum: ["HIDDEN", "VISIBLE", "UNKNOWN"],
  },
  OutletWorkingScheduleDTO: {
    kind: "object",
    properties: {
      workInHoliday: { kind: "boolean" },
      scheduleItems: {
        kind: "array",
        items: { kind: "ref", name: "OutletWorkingScheduleItemDTO" },
      },
    },
    required: ["scheduleItems"],
  },
  OutletWorkingScheduleItemDTO: {
    kind: "object",
    properties: {
      startDay: { kind: "ref", name: "DayOfWeekType" },
      endDay: { kind: "ref", name: "DayOfWeekType" },
      startTime: { kind: "string" },
      endTime: { kind: "string" },
    },
    required: ["startDay", "endDay", "startTime", "endTime"],
  },
  PackagingForwardScrollingPagerDTO: {
    kind: "object",
    properties: { nextPageToken: { kind: "string" } },
    required: [],
  },
  RegionDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      name: { kind: "string" },
      type: { kind: "ref", name: "RegionType" },
      parent: { kind: "ref", name: "RegionDTO" },
    },
    required: ["id", "name", "type"],
  },
  RegionType: {
    kind: "string",
    enum: [
      "OTHER",
      "CONTINENT",
      "REGION",
      "COUNTRY",
      "COUNTRY_DISTRICT",
      "REPUBLIC",
      "CITY",
      "VILLAGE",
      "CITY_DISTRICT",
      "SUBWAY_STATION",
      "REPUBLIC_AREA",
    ],
  },
};
