// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const priceQuarantineComponents: YmSchemaComponents = {
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLockedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  BasePriceDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  ConfirmPricesRequest: {
    kind: "object",
    properties: {
      offerIds: { kind: "array", items: { kind: "ref", name: "ShopSku" } },
    },
    required: ["offerIds"],
  },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  EmptyApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  GetQuarantineOffersRequest: {
    kind: "object",
    properties: {
      offerIds: {
        kind: "array",
        items: { kind: "ref", name: "ShopSku" },
        nullable: true,
      },
      cardStatuses: {
        kind: "array",
        items: { kind: "ref", name: "OfferCardStatusType" },
        nullable: true,
      },
      categoryIds: {
        kind: "array",
        items: { kind: "number", integer: true, minimum: 0 },
        nullable: true,
      },
      vendorNames: { kind: "array", items: { kind: "string" }, nullable: true },
      tags: { kind: "array", items: { kind: "string" }, nullable: true },
    },
    required: [],
  },
  GetQuarantineOffersResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GetQuarantineOffersResultDTO" },
    },
    required: ["status"],
  },
  GetQuarantineOffersResultDTO: {
    kind: "object",
    properties: {
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
      offers: {
        kind: "array",
        items: { kind: "ref", name: "QuarantineOfferDTO" },
      },
    },
    required: ["offers"],
  },
  OfferCardStatusType: {
    kind: "string",
    enum: [
      "HAS_CARD_CAN_NOT_UPDATE",
      "HAS_CARD_CAN_UPDATE",
      "HAS_CARD_CAN_UPDATE_ERRORS",
      "HAS_CARD_CAN_UPDATE_PROCESSING",
      "NO_CARD_NEED_CONTENT",
      "NO_CARD_MARKET_WILL_CREATE",
      "NO_CARD_ERRORS",
      "NO_CARD_PROCESSING",
      "NO_CARD_ADD_TO_CAMPAIGN",
    ],
  },
  PackagingForwardScrollingPagerDTO: {
    kind: "object",
    properties: { nextPageToken: { kind: "string" } },
    required: [],
  },
  PriceQuarantineVerdictDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "PriceQuarantineVerdictType" },
      params: {
        kind: "array",
        items: { kind: "ref", name: "PriceQuarantineVerdictParameterDTO" },
      },
    },
    required: ["params"],
  },
  PriceQuarantineVerdictParamNameType: {
    kind: "string",
    enum: ["CURRENT_PRICE", "LAST_VALID_PRICE", "MIN_PRICE", "CURRENCY"],
  },
  PriceQuarantineVerdictParameterDTO: {
    kind: "object",
    properties: {
      name: { kind: "ref", name: "PriceQuarantineVerdictParamNameType" },
      value: { kind: "string" },
    },
    required: ["name", "value"],
  },
  PriceQuarantineVerdictType: {
    kind: "string",
    enum: ["PRICE_CHANGE", "LOW_PRICE", "LOW_PRICE_PROMO"],
  },
  QuarantineOfferDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      currentPrice: { kind: "ref", name: "BasePriceDTO" },
      lastValidPrice: { kind: "ref", name: "BasePriceDTO" },
      verdicts: {
        kind: "array",
        items: { kind: "ref", name: "PriceQuarantineVerdictDTO" },
        nullable: true,
      },
    },
    required: [],
  },
  ShopSku: { kind: "string", minLength: 1, maxLength: 255 },
};
