// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const pricesComponents: YmSchemaComponents = {
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLockedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  BasePriceDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  DiscountBase: { kind: "number", minimum: 0 },
  EmptyApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  GetDefaultPricesRequest: {
    kind: "object",
    properties: {
      offerIds: {
        kind: "array",
        items: { kind: "ref", name: "ShopSku" },
        nullable: true,
      },
      archived: { kind: "boolean" },
    },
    required: [],
  },
  GetDefaultPricesResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "OfferDefaultPriceListResponseDTO" },
    },
    required: ["status"],
  },
  GetPricesByOfferIdsRequest: {
    kind: "object",
    properties: {
      offerIds: {
        kind: "array",
        items: { kind: "ref", name: "ShopSku" },
        nullable: true,
      },
    },
    required: [],
  },
  GetPricesByOfferIdsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "OfferPriceByOfferIdsListResponseDTO" },
    },
    required: ["status"],
  },
  GetPricesResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "OfferPriceListResponseDTO" },
    },
    required: ["status"],
  },
  MarketSku: { kind: "number", integer: true, minimum: 1 },
  OfferDefaultPriceDTO: {
    kind: "object",
    properties: {
      minimumForBestseller: { kind: "number", minimum: 0, maximum: 100000000 },
      excludedFromBestsellers: { kind: "boolean" },
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
      discountBase: { kind: "ref", name: "DiscountBase" },
      updatedAt: { kind: "string" },
    },
    required: [],
  },
  OfferDefaultPriceListResponseDTO: {
    kind: "object",
    properties: {
      offers: {
        kind: "array",
        items: { kind: "ref", name: "OfferDefaultPriceResponseDTO" },
      },
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
    },
    required: ["offers"],
  },
  OfferDefaultPriceResponseDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      price: { kind: "ref", name: "OfferDefaultPriceDTO" },
    },
    required: ["offerId"],
  },
  OfferPriceByOfferIdsListResponseDTO: {
    kind: "object",
    properties: {
      offers: {
        kind: "array",
        items: { kind: "ref", name: "OfferPriceByOfferIdsResponseDTO" },
      },
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
    },
    required: ["offers"],
  },
  OfferPriceByOfferIdsResponseDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      price: { kind: "ref", name: "PriceDTO" },
      updatedAt: { kind: "string" },
    },
    required: [],
  },
  OfferPriceDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      price: { kind: "ref", name: "PriceDTO" },
    },
    required: [],
  },
  OfferPriceListResponseDTO: {
    kind: "object",
    properties: {
      offers: {
        kind: "array",
        items: { kind: "ref", name: "OfferPriceResponseDTO" },
      },
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
      total: { kind: "number", integer: true },
    },
    required: ["offers"],
  },
  OfferPriceResponseDTO: {
    kind: "object",
    properties: {
      id: { kind: "string" },
      price: { kind: "ref", name: "PriceDTO" },
      marketSku: { kind: "ref", name: "MarketSku" },
      updatedAt: { kind: "string" },
    },
    required: [],
  },
  PackagingForwardScrollingPagerDTO: {
    kind: "object",
    properties: { nextPageToken: { kind: "string" } },
    required: [],
  },
  PriceDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      discountBase: { kind: "ref", name: "DiscountBase" },
      currencyId: { kind: "ref", name: "CurrencyType" },
      vat: { kind: "ref", name: "VatType" },
    },
    required: [],
  },
  PriceWithDiscountDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
      discountBase: { kind: "ref", name: "DiscountBase" },
    },
    required: ["value", "currencyId"],
  },
  ShopSku: { kind: "string", minLength: 1, maxLength: 255 },
  UpdateBusinessOfferPriceDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      price: { kind: "ref", name: "UpdateBusinessPricesDTO" },
    },
    required: ["offerId", "price"],
  },
  UpdateBusinessPricesDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
      discountBase: { kind: "ref", name: "DiscountBase" },
      minimumForBestseller: { kind: "number", minimum: 0, maximum: 100000000 },
    },
    required: ["value", "currencyId"],
  },
  UpdateBusinessPricesRequest: {
    kind: "object",
    properties: {
      offers: {
        kind: "array",
        items: { kind: "ref", name: "UpdateBusinessOfferPriceDTO" },
      },
    },
    required: ["offers"],
  },
  UpdatePricesRequest: {
    kind: "object",
    properties: {
      offers: { kind: "array", items: { kind: "ref", name: "OfferPriceDTO" } },
    },
    required: ["offers"],
  },
  VatType: { kind: "number", integer: true },
};
