// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const returnsComponents: YmSchemaComponents = {
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  BasePriceDTO: {
    kind: "object",
    properties: {
      value: { kind: "number", minimum: 0 },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  CampaignId: { kind: "number", integer: true, minimum: 1 },
  CancelReturnDTO: {
    kind: "object",
    properties: { operation: { kind: "ref", name: "OperationDTO" } },
    required: ["operation"],
  },
  CancelReturnRequest: {
    kind: "object",
    properties: { returnId: { kind: "number", integer: true } },
    required: ["returnId"],
  },
  CancelReturnResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "CancelReturnDTO" },
    },
    required: ["status"],
  },
  CreateReturnDTO: {
    kind: "object",
    properties: {
      externalReturnId: { kind: "string", minLength: 1 },
      orderId: { kind: "number", integer: true },
      items: {
        kind: "array",
        items: { kind: "ref", name: "CreateReturnItemDTO" },
      },
      customer: { kind: "ref", name: "CustomerDTO" },
      returnOption: { kind: "ref", name: "CreateReturnOptionDTO" },
    },
    required: [
      "externalReturnId",
      "orderId",
      "items",
      "customer",
      "returnOption",
    ],
  },
  CreateReturnItemDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      count: { kind: "number", integer: true, minimum: 1, maximum: 1000 },
      reasonType: { kind: "ref", name: "ExternalReturnDecisionReasonType" },
      subreasonType: {
        kind: "ref",
        name: "ExternalReturnDecisionSubreasonType",
      },
      comment: { kind: "string", minLength: 1, maxLength: 3000 },
      pictures: {
        kind: "array",
        items: { kind: "string", minLength: 1, maxLength: 2000 },
        nullable: true,
      },
    },
    required: ["offerId", "count", "reasonType", "subreasonType"],
  },
  CreateReturnOptionDTO: {
    kind: "object",
    properties: { pickupReturn: { kind: "ref", name: "OrderPickupReturnDTO" } },
    required: ["pickupReturn"],
  },
  CreateReturnRequest: {
    kind: "object",
    properties: { newReturn: { kind: "ref", name: "CreateReturnDTO" } },
    required: ["newReturn"],
  },
  CreateReturnResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "CreatedReturnDTO" },
    },
    required: ["status"],
  },
  CreatedReturnDTO: {
    kind: "object",
    properties: { id: { kind: "number", integer: true } },
    required: ["id"],
  },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  CurrencyValueDTO: {
    kind: "object",
    properties: {
      value: { kind: "number" },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  CustomerDTO: {
    kind: "object",
    properties: {
      firstName: { kind: "string", minLength: 1, maxLength: 512 },
      lastName: { kind: "string", minLength: 1, maxLength: 512 },
      middleName: { kind: "string", minLength: 1, maxLength: 512 },
      phone: { kind: "string", minLength: 5, maxLength: 16 },
    },
    required: ["firstName", "lastName", "phone"],
  },
  EmptyApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ExternalReturnDecisionReasonType: {
    kind: "string",
    enum: ["BAD_QUALITY", "DOES_NOT_FIT", "WRONG_ITEM"],
  },
  ExternalReturnDecisionSubreasonType: {
    kind: "string",
    enum: [
      "USER_DID_NOT_LIKE",
      "USER_CHANGED_MIND",
      "DELIVERED_TOO_LONG",
      "BAD_PACKAGE",
      "DAMAGED",
      "NOT_WORKING",
      "INCOMPLETENESS",
      "WRONG_ITEM",
      "WRONG_COLOR",
      "DID_NOT_MATCH_DESCRIPTION",
    ],
  },
  GetReturnAvailableDecisionsRequest: {
    kind: "object",
    properties: {
      campaignId: { kind: "ref", name: "CampaignId" },
      returnId: { kind: "ref", name: "ReturnId" },
    },
    required: ["campaignId", "returnId"],
  },
  GetReturnAvailableDecisionsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "ReturnAvailableDecisionsResponse" },
    },
    required: ["status"],
  },
  GetReturnResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "ReturnDTO" },
    },
    required: ["status"],
  },
  GetReturnsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "PagedReturnsDTO" },
    },
    required: ["status"],
  },
  LogisticPickupPointDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      name: { kind: "string" },
      address: { kind: "ref", name: "PickupAddressDTO" },
      instruction: { kind: "string" },
      type: { kind: "ref", name: "LogisticPointType" },
      logisticPartnerId: { kind: "number", integer: true },
    },
    required: [],
  },
  LogisticPointId: { kind: "number", integer: true, minimum: 1 },
  LogisticPointType: {
    kind: "string",
    enum: [
      "WAREHOUSE",
      "PICKUP_POINT",
      "PICKUP_TERMINAL",
      "PICKUP_POST_OFFICE",
      "PICKUP_MIXED",
      "PICKUP_RETAIL",
    ],
  },
  MarketSku: { kind: "number", integer: true, minimum: 1 },
  OperationDTO: {
    kind: "object",
    properties: {
      id: { kind: "ref", name: "OperationId" },
      type: { kind: "ref", name: "OperationType" },
    },
    required: ["id", "type"],
  },
  OperationId: { kind: "string", minLength: 1, maxLength: 1000 },
  OperationType: {
    kind: "string",
    enum: [
      "ORDER_RECIPIENT_UPDATE",
      "ORDER_DELIVERY_INTERVAL_UPDATE",
      "ORDER_STATUS_UPDATE",
      "RETURN_CANCELLATION",
    ],
  },
  OrderPickupReturnDTO: {
    kind: "object",
    properties: { logisticPointId: { kind: "ref", name: "LogisticPointId" } },
    required: ["logisticPointId"],
  },
  PackagingForwardScrollingPagerDTO: {
    kind: "object",
    properties: { nextPageToken: { kind: "string" } },
    required: [],
  },
  PagedReturnsDTO: {
    kind: "object",
    properties: {
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
      returns: { kind: "array", items: { kind: "ref", name: "ReturnDTO" } },
    },
    required: ["returns"],
  },
  PartialCompensationBoundsDTO: {
    kind: "object",
    properties: {
      minAmount: { kind: "ref", name: "BasePriceDTO" },
      maxAmount: { kind: "ref", name: "BasePriceDTO" },
      maxPercent: { kind: "number", integer: true },
    },
    required: ["minAmount", "maxAmount", "maxPercent"],
  },
  PickupAddressDTO: {
    kind: "object",
    properties: {
      country: { kind: "string" },
      city: { kind: "string" },
      street: { kind: "string" },
      house: { kind: "string" },
      postcode: { kind: "string" },
    },
    required: [],
  },
  RecipientType: { kind: "string", enum: ["SHOP", "DELIVERY_SERVICE", "POST"] },
  RefundStatusType: {
    kind: "string",
    enum: [
      "STARTED_BY_USER",
      "REFUND_IN_PROGRESS",
      "REFUNDED",
      "FAILED",
      "WAITING_FOR_DECISION",
      "DECISION_MADE",
      "REFUNDED_WITH_BONUSES",
      "REFUNDED_BY_SHOP",
      "CANCELLED",
      "REJECTED",
      "COMPLETE_WITHOUT_REFUND",
      "PREMODERATION_DISPUTE",
      "PREMODERATION_DECISION_WAITING",
      "PREMODERATION_DECISION_MADE",
      "PREMODERATION_SELECT_DELIVERY",
      "UNKNOWN",
    ],
  },
  ReturnAvailableDecisionDTO: {
    kind: "object",
    properties: {
      decisionType: { kind: "ref", name: "ReturnDecisionType" },
      decisionReasonTypes: {
        kind: "array",
        items: { kind: "ref", name: "ReturnRequestDecisionReasonType" },
        nullable: true,
      },
      partialCompensationBounds: {
        kind: "ref",
        name: "PartialCompensationBoundsDTO",
      },
    },
    required: ["decisionType"],
  },
  ReturnAvailableDecisionsResponse: {
    kind: "object",
    properties: {
      availableDecisions: {
        kind: "array",
        items: { kind: "ref", name: "ReturnAvailableDecisionDTO" },
      },
    },
    required: ["availableDecisions"],
  },
  ReturnDTO: {
    kind: "object",
    properties: {
      id: { kind: "number", integer: true },
      orderId: { kind: "number", integer: true },
      creationDate: { kind: "string" },
      updateDate: { kind: "string" },
      refundStatus: { kind: "ref", name: "RefundStatusType" },
      logisticPickupPoint: { kind: "ref", name: "LogisticPickupPointDTO" },
      pickupTillDate: { kind: "string" },
      shipmentRecipientType: { kind: "ref", name: "RecipientType" },
      shipmentStatus: { kind: "ref", name: "ReturnShipmentStatusType" },
      refundAmount: { kind: "number", integer: true },
      amount: { kind: "ref", name: "CurrencyValueDTO" },
      items: { kind: "array", items: { kind: "ref", name: "ReturnItemDTO" } },
      returnType: { kind: "ref", name: "ReturnType" },
      fastReturn: { kind: "boolean" },
    },
    required: ["id", "orderId", "items", "returnType"],
  },
  ReturnDecisionDTO: {
    kind: "object",
    properties: {
      returnItemId: { kind: "number", integer: true },
      count: { kind: "number", integer: true },
      comment: { kind: "string" },
      reasonType: { kind: "ref", name: "ReturnDecisionReasonType" },
      subreasonType: { kind: "ref", name: "ReturnDecisionSubreasonType" },
      decisionType: { kind: "ref", name: "ReturnDecisionType" },
      refundAmount: { kind: "number", integer: true },
      amount: { kind: "ref", name: "CurrencyValueDTO" },
      partnerCompensation: { kind: "number", integer: true },
      partnerCompensationAmount: { kind: "ref", name: "CurrencyValueDTO" },
      images: { kind: "array", items: { kind: "string" }, nullable: true },
    },
    required: [],
  },
  ReturnDecisionReasonType: {
    kind: "string",
    enum: [
      "BAD_QUALITY",
      "DOES_NOT_FIT",
      "WRONG_ITEM",
      "DAMAGE_DELIVERY",
      "LOYALTY_FAIL",
      "CONTENT_FAIL",
      "DELIVERY_FAIL",
      "UNKNOWN",
    ],
  },
  ReturnDecisionSubreasonType: {
    kind: "string",
    enum: [
      "USER_DID_NOT_LIKE",
      "USER_CHANGED_MIND",
      "DELIVERED_TOO_LONG",
      "BAD_PACKAGE",
      "DAMAGED",
      "NOT_WORKING",
      "INCOMPLETENESS",
      "WRONG_ITEM",
      "WRONG_COLOR",
      "DID_NOT_MATCH_DESCRIPTION",
      "WRONG_ORDER",
      "WRONG_AMOUNT_DELIVERED",
      "WRAPPING_DAMAGED",
      "ITEM_WAS_USED",
      "BROKEN",
      "BAD_FLOWERS",
      "PARCEL_MISSING",
      "INCOMPLETE",
      "UNKNOWN",
    ],
  },
  ReturnDecisionType: {
    kind: "string",
    enum: [
      "FAST_REFUND_MONEY",
      "REFUND_MONEY",
      "REFUND_MONEY_INCLUDING_SHIPMENT",
      "REPAIR",
      "REPLACE",
      "SEND_TO_EXAMINATION",
      "DECLINE_REFUND",
      "PARTIAL_MONEY_REFUND",
      "OTHER_DECISION",
      "UNKNOWN",
    ],
  },
  ReturnId: { kind: "number", integer: true, minimum: 1 },
  ReturnInstanceDTO: {
    kind: "object",
    properties: {
      stockType: { kind: "ref", name: "ReturnInstanceStockType" },
      status: { kind: "ref", name: "ReturnInstanceStatusType" },
      cis: { kind: "string" },
      imei: { kind: "string" },
    },
    required: [],
  },
  ReturnInstanceStatusType: {
    kind: "string",
    enum: [
      "CREATED",
      "RECEIVED",
      "IN_TRANSIT",
      "READY_FOR_PICKUP",
      "PICKED",
      "RECEIVED_ON_FULFILLMENT",
      "CANCELLED",
      "LOST",
      "UTILIZED",
      "PREPARED_FOR_UTILIZATION",
      "EXPROPRIATED",
      "NOT_IN_DEMAND",
    ],
  },
  ReturnInstanceStockType: {
    kind: "string",
    enum: [
      "FIT",
      "DEFECT",
      "ANOMALY",
      "SURPLUS",
      "EXPIRED",
      "MISGRADING",
      "UNDEFINED",
      "INCORRECT_IMEI",
      "INCORRECT_SERIAL_NUMBER",
      "INCORRECT_CIS",
      "PART_MISSING",
      "NON_COMPLIENT",
      "NOT_ACCEPTABLE",
      "SERVICE",
      "MARKDOWN",
      "DEMO",
      "REPAIR",
      "FIRMWARE",
      "UNKNOWN",
    ],
  },
  ReturnItemDTO: {
    kind: "object",
    properties: {
      marketSku: { kind: "ref", name: "MarketSku" },
      shopSku: { kind: "ref", name: "ShopSku" },
      count: { kind: "number", integer: true },
      decisions: {
        kind: "array",
        items: { kind: "ref", name: "ReturnDecisionDTO" },
        nullable: true,
      },
      instances: {
        kind: "array",
        items: { kind: "ref", name: "ReturnInstanceDTO" },
        nullable: true,
      },
      tracks: {
        kind: "array",
        items: { kind: "ref", name: "TrackDTO" },
        nullable: true,
      },
    },
    required: ["shopSku", "count"],
  },
  ReturnItemDecisionComment: { kind: "string" },
  ReturnItemDecisionDTO: {
    kind: "object",
    properties: {
      returnItemId: { kind: "ref", name: "ReturnItemId" },
      decisionType: { kind: "ref", name: "ReturnRequestDecisionType" },
      decisionReasonType: {
        kind: "ref",
        name: "ReturnRequestDecisionReasonType",
      },
      comment: { kind: "ref", name: "ReturnItemDecisionComment" },
      compensation: { kind: "ref", name: "BasePriceDTO" },
    },
    required: ["returnItemId", "decisionType"],
  },
  ReturnItemId: { kind: "number", integer: true },
  ReturnRequestDecisionReasonType: {
    kind: "string",
    enum: [
      "ISSUE_WITH_THE_PRODUCT_WAS_NOT_CONFIRMED",
      "MECHANICAL_DAMAGE",
      "WARRANTY_PERIOD_HAS_EXPIRED",
      "CONFIGURATION_OR_PACKAGING_COMPROMISED",
      "PRODUCT_APPEARANCE_COMPROMISED",
      "WARRANTY_TERMS_VIOLATED",
      "DEVICE_ACTIVATED",
    ],
  },
  ReturnRequestDecisionType: {
    kind: "string",
    enum: [
      "FAST_REFUND_MONEY",
      "REFUND_MONEY",
      "REFUND_MONEY_INCLUDING_SHIPMENT",
      "REPAIR",
      "REPLACE",
      "SEND_TO_EXAMINATION",
      "DECLINE_REFUND",
      "PARTIAL_MONEY_REFUND",
      "OTHER_DECISION",
    ],
  },
  ReturnShipmentStatusType: {
    kind: "string",
    enum: [
      "CREATED",
      "RECEIVED",
      "IN_TRANSIT",
      "READY_FOR_PICKUP",
      "PICKED",
      "LOST",
      "EXPIRED",
      "CANCELLED",
      "FULFILMENT_RECEIVED",
      "PREPARED_FOR_UTILIZATION",
      "NOT_IN_DEMAND",
      "UTILIZED",
      "READY_FOR_EXPROPRIATION",
      "RECEIVED_FOR_EXPROPRIATION",
      "UNKNOWN",
    ],
  },
  ReturnType: { kind: "string", enum: ["UNREDEEMED", "RETURN"] },
  SetReturnDecisionRequest: {
    kind: "object",
    properties: {
      returnItemId: { kind: "ref", name: "ReturnItemId" },
      decisionType: { kind: "ref", name: "ReturnRequestDecisionType" },
      comment: { kind: "ref", name: "ReturnItemDecisionComment" },
      compensation: { kind: "ref", name: "BasePriceDTO" },
    },
    required: ["returnItemId", "decisionType"],
  },
  ShopSku: { kind: "string", minLength: 1, maxLength: 255 },
  SubmitReturnDecisionRequest: {
    kind: "object",
    properties: {
      returnItemDecisions: {
        kind: "array",
        items: { kind: "ref", name: "ReturnItemDecisionDTO" },
      },
    },
    required: ["returnItemDecisions"],
  },
  TrackDTO: {
    kind: "object",
    properties: { trackCode: { kind: "string" } },
    required: [],
  },
};
