// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const supplyRequestsComponents: YmSchemaComponents = {
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  CurrencyValueDTO: {
    kind: "object",
    properties: {
      value: { kind: "number" },
      currencyId: { kind: "ref", name: "CurrencyType" },
    },
    required: ["value", "currencyId"],
  },
  GetSupplyRequestDocumentsDTO: {
    kind: "object",
    properties: {
      documents: {
        kind: "array",
        items: { kind: "ref", name: "SupplyRequestDocumentDTO" },
      },
    },
    required: ["documents"],
  },
  GetSupplyRequestDocumentsRequest: {
    kind: "object",
    properties: { requestId: { kind: "ref", name: "SupplyRequestId" } },
    required: ["requestId"],
  },
  GetSupplyRequestDocumentsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GetSupplyRequestDocumentsDTO" },
    },
    required: ["status"],
  },
  GetSupplyRequestItemsDTO: {
    kind: "object",
    properties: {
      items: {
        kind: "array",
        items: { kind: "ref", name: "SupplyRequestItemDTO" },
      },
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
    },
    required: ["items"],
  },
  GetSupplyRequestItemsRequest: {
    kind: "object",
    properties: { requestId: { kind: "ref", name: "SupplyRequestId" } },
    required: ["requestId"],
  },
  GetSupplyRequestItemsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GetSupplyRequestItemsDTO" },
    },
    required: ["status"],
  },
  GetSupplyRequestsDTO: {
    kind: "object",
    properties: {
      requests: {
        kind: "array",
        items: { kind: "ref", name: "SupplyRequestDTO" },
      },
      paging: { kind: "ref", name: "PackagingForwardScrollingPagerDTO" },
    },
    required: ["requests"],
  },
  GetSupplyRequestsRequest: {
    kind: "object",
    properties: {
      requestIds: {
        kind: "array",
        items: { kind: "ref", name: "SupplyRequestId" },
        nullable: true,
      },
      requestDateFrom: { kind: "string", nullable: true },
      requestDateTo: { kind: "string", nullable: true },
      requestTypes: {
        kind: "array",
        items: { kind: "ref", name: "SupplyRequestType" },
        nullable: true,
      },
      requestSubtypes: {
        kind: "array",
        items: { kind: "ref", name: "SupplyRequestSubType" },
        nullable: true,
      },
      requestStatuses: {
        kind: "array",
        items: { kind: "ref", name: "SupplyRequestStatusType" },
        nullable: true,
      },
      sorting: { kind: "ref", name: "SupplyRequestSortingDTO" },
    },
    required: [],
  },
  GetSupplyRequestsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "GetSupplyRequestsDTO" },
    },
    required: ["status"],
  },
  GpsDTO: {
    kind: "object",
    properties: { latitude: { kind: "number" }, longitude: { kind: "number" } },
    required: ["latitude", "longitude"],
  },
  PackagingForwardScrollingPagerDTO: {
    kind: "object",
    properties: { nextPageToken: { kind: "string" } },
    required: [],
  },
  ShopSku: { kind: "string", minLength: 1, maxLength: 255 },
  SortOrderType: { kind: "string", enum: ["ASC", "DESC"] },
  SupplyRequestCountersDTO: {
    kind: "object",
    properties: {
      planCount: { kind: "number", integer: true, minimum: 0 },
      factCount: { kind: "number", integer: true, minimum: 0 },
      undefinedCount: { kind: "number", integer: true, minimum: 0 },
      surplusCount: { kind: "number", integer: true, minimum: 0 },
      shortageCount: { kind: "number", integer: true, minimum: 0 },
      defectCount: { kind: "number", integer: true, minimum: 0 },
      acceptableCount: { kind: "number", integer: true, minimum: 0 },
      unacceptableCount: { kind: "number", integer: true, minimum: 0 },
      actualPalletsCount: { kind: "number", integer: true, minimum: 0 },
      actualBoxCount: { kind: "number", integer: true, minimum: 0 },
    },
    required: [],
  },
  SupplyRequestDTO: {
    kind: "object",
    properties: {
      id: { kind: "ref", name: "SupplyRequestIdDTO" },
      type: { kind: "ref", name: "SupplyRequestType" },
      subtype: { kind: "ref", name: "SupplyRequestSubType" },
      status: { kind: "ref", name: "SupplyRequestStatusType" },
      updatedAt: { kind: "string" },
      counters: { kind: "ref", name: "SupplyRequestCountersDTO" },
      parentLink: {
        kind: "ref",
        name: "SupplyRequestReferenceDTO",
        nullable: true,
      },
      childrenLinks: {
        kind: "array",
        items: { kind: "ref", name: "SupplyRequestReferenceDTO" },
        nullable: true,
      },
      targetLocation: { kind: "ref", name: "SupplyRequestLocationDTO" },
      transitLocation: { kind: "ref", name: "SupplyRequestLocationDTO" },
    },
    required: [
      "id",
      "type",
      "subtype",
      "status",
      "updatedAt",
      "counters",
      "targetLocation",
    ],
  },
  SupplyRequestDocumentDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "SupplyRequestDocumentType" },
      url: { kind: "ref", name: "Url" },
      createdAt: { kind: "string" },
    },
    required: ["url", "type", "createdAt"],
  },
  SupplyRequestDocumentType: {
    kind: "string",
    enum: [
      "SUPPLY",
      "ADDITIONAL_SUPPLY",
      "VIRTUAL_DISTRIBUTION_CENTER_SUPPLY",
      "TRANSFER",
      "INBOUND_UTD",
      "OUTBOUND_UTD",
      "ADDITIONAL_SUPPLY_ACCEPTABLE_GOODS",
      "ADDITIONAL_SUPPLY_UNACCEPTABLE_GOODS",
      "VALIDATION_ERRORS",
      "WITHDRAW",
      "ACT_OF_WITHDRAW",
      "ANOMALY_CONTAINERS_WITHDRAW_ACT",
      "ACT_OF_WITHDRAW_FROM_STORAGE",
      "ACT_OF_RECEPTION_TRANSFER",
      "ACT_OF_DISCREPANCY",
      "SECONDARY_RECEPTION_ACT",
      "CARGO_UNITS",
      "IDENTIFIERS",
      "CIS_FACT",
      "ITEMS_WITH_CISES",
      "REPORT_OF_WITHDRAW_WITH_CISES",
      "SECONDARY_ACCEPTANCE_CISES",
      "RNPT_FACT",
    ],
  },
  SupplyRequestId: { kind: "number", integer: true, minimum: 1 },
  SupplyRequestIdDTO: {
    kind: "object",
    properties: {
      id: { kind: "ref", name: "SupplyRequestId" },
      marketplaceRequestId: { kind: "string" },
      warehouseRequestId: { kind: "string" },
    },
    required: ["id"],
  },
  SupplyRequestItemCountersDTO: {
    kind: "object",
    properties: {
      planCount: { kind: "number", integer: true, minimum: 0 },
      factCount: { kind: "number", integer: true, minimum: 0 },
      surplusCount: { kind: "number", integer: true, minimum: 0 },
      shortageCount: { kind: "number", integer: true, minimum: 0 },
      defectCount: { kind: "number", integer: true, minimum: 0 },
    },
    required: [],
  },
  SupplyRequestItemDTO: {
    kind: "object",
    properties: {
      offerId: { kind: "ref", name: "ShopSku" },
      name: { kind: "string" },
      price: { kind: "ref", name: "CurrencyValueDTO" },
      counters: { kind: "ref", name: "SupplyRequestItemCountersDTO" },
    },
    required: ["offerId", "name", "counters"],
  },
  SupplyRequestLocationAddressDTO: {
    kind: "object",
    properties: {
      fullAddress: { kind: "string" },
      gps: { kind: "ref", name: "GpsDTO" },
    },
    required: ["fullAddress", "gps"],
  },
  SupplyRequestLocationDTO: {
    kind: "object",
    properties: {
      requestedDate: { kind: "string" },
      serviceId: { kind: "number", integer: true },
      name: { kind: "string" },
      address: { kind: "ref", name: "SupplyRequestLocationAddressDTO" },
      type: { kind: "ref", name: "SupplyRequestLocationType" },
    },
    required: ["serviceId", "name", "address", "type"],
  },
  SupplyRequestLocationType: {
    kind: "string",
    enum: ["FULFILLMENT", "XDOC", "PICKUP_POINT"],
  },
  SupplyRequestReferenceDTO: {
    kind: "object",
    properties: {
      id: { kind: "ref", name: "SupplyRequestIdDTO" },
      type: { kind: "ref", name: "SupplyRequestReferenceType" },
    },
    required: ["id", "type"],
  },
  SupplyRequestReferenceType: {
    kind: "string",
    enum: [
      "VIRTUAL_DISTRIBUTION",
      "WITHDRAW",
      "UTILIZATION",
      "ADDITIONAL_SUPPLY",
    ],
  },
  SupplyRequestSortAttributeType: {
    kind: "string",
    enum: ["ID", "REQUESTED_DATE", "UPDATED_AT", "STATUS"],
  },
  SupplyRequestSortingDTO: {
    kind: "object",
    properties: {
      direction: { kind: "ref", name: "SortOrderType" },
      attribute: { kind: "ref", name: "SupplyRequestSortAttributeType" },
    },
    required: ["direction", "attribute"],
  },
  SupplyRequestStatusType: {
    kind: "string",
    enum: [
      "CREATED",
      "FINISHED",
      "CANCELLED",
      "INVALID",
      "VALIDATED",
      "PUBLISHED",
      "ARRIVED_TO_SERVICE",
      "ARRIVED_TO_XDOC_SERVICE",
      "SHIPPED_TO_SERVICE",
      "CANCELLATION_REQUESTED",
      "CANCELLATION_REJECTED",
      "REGISTERED_IN_ELECTRONIC_QUEUE",
      "READY_FOR_UTILIZATION",
      "TRANSIT_MOVING",
      "WAREHOUSE_HANDLING",
      "ACCEPTED_BY_WAREHOUSE_SYSTEM",
      "READY_TO_WITHDRAW",
      "NEED_PREPARATION",
      "WAREHOUSE_SIGNED_ACT",
    ],
  },
  SupplyRequestSubType: {
    kind: "string",
    enum: [
      "DEFAULT",
      "XDOC",
      "INVENTORYING_SUPPLY",
      "INVENTORYING_SUPPLY_WAREHOUSE_BASED_PER_SUPPLIER",
      "MOVEMENT_SUPPLY",
      "ADDITIONAL_SUPPLY",
      "VIRTUAL_DISTRIBUTION_CENTER",
      "VIRTUAL_DISTRIBUTION_CENTER_CHILD",
      "FORCE_PLAN",
      "FORCE_PLAN_ANOMALY_PER_SUPPLY",
      "PLAN_BY_SUPPLIER",
      "ANOMALY_WITHDRAW",
      "FIX_LOST_INVENTORYING",
      "OPER_LOST_INVENTORYING",
      "MOVEMENT_WITHDRAW",
      "MISGRADING_SUPPLY",
      "MISGRADING_WITHDRAW",
      "MAN_UTIL",
      "WITHDRAW_AUTO_UTILIZATION",
      "EXTERNAL_WITHDRAW_INT_OZON",
      "EXTERNAL_WITHDRAW_INT_WB",
    ],
  },
  SupplyRequestType: {
    kind: "string",
    enum: ["SUPPLY", "WITHDRAW", "UTILIZATION"],
  },
  Url: { kind: "string", minLength: 1, maxLength: 2000 },
};
