// Generated runtime schemas for this Yandex Market API domain.
import type { YmSchemaComponents } from "../schema.js";

export const tariffsComponents: YmSchemaComponents = {
  ApiClientDataErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiErrorDTO: {
    kind: "object",
    properties: { code: { kind: "string" }, message: { kind: "string" } },
    required: ["code"],
  },
  ApiErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiForbiddenErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiLimitErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiNotFoundErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiResponse: {
    kind: "object",
    properties: { status: { kind: "ref", name: "ApiResponseStatusType" } },
    required: ["status"],
  },
  ApiResponseStatusType: { kind: "string", enum: ["OK", "ERROR"] },
  ApiServerErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  ApiUnauthorizedErrorResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      errors: {
        kind: "array",
        items: { kind: "ref", name: "ApiErrorDTO" },
        nullable: true,
      },
    },
    required: ["status"],
  },
  CalculateTariffsOfferDTO: {
    kind: "object",
    properties: {
      categoryId: { kind: "number", integer: true, minimum: 0 },
      price: { kind: "number", minimum: 0 },
      length: { kind: "number", minimum: 0 },
      width: { kind: "number", minimum: 0 },
      height: { kind: "number", minimum: 0 },
      weight: { kind: "number", minimum: 0 },
      quantity: { kind: "number", integer: true, minimum: 1 },
    },
    required: ["categoryId", "price", "length", "width", "height", "weight"],
  },
  CalculateTariffsOfferInfoDTO: {
    kind: "object",
    properties: {
      offer: { kind: "ref", name: "CalculateTariffsOfferDTO" },
      tariffs: {
        kind: "array",
        items: { kind: "ref", name: "CalculatedTariffDTO" },
      },
    },
    required: ["offer", "tariffs"],
  },
  CalculateTariffsParametersDTO: {
    kind: "object",
    properties: {
      campaignId: { kind: "ref", name: "CampaignId" },
      sellingProgram: { kind: "ref", name: "SellingProgramType" },
      frequency: { kind: "ref", name: "PaymentFrequencyType" },
      paymentDelayWeeks: {
        kind: "number",
        integer: true,
        minimum: 0,
        maximum: 4,
      },
      currency: { kind: "ref", name: "CurrencyType" },
    },
    required: [],
  },
  CalculateTariffsRequest: {
    kind: "object",
    properties: {
      parameters: { kind: "ref", name: "CalculateTariffsParametersDTO" },
      offers: {
        kind: "array",
        items: { kind: "ref", name: "CalculateTariffsOfferDTO" },
      },
    },
    required: ["parameters", "offers"],
  },
  CalculateTariffsResponse: {
    kind: "object",
    properties: {
      status: { kind: "ref", name: "ApiResponseStatusType" },
      result: { kind: "ref", name: "CalculateTariffsResponseDTO" },
    },
    required: ["status"],
  },
  CalculateTariffsResponseDTO: {
    kind: "object",
    properties: {
      offers: {
        kind: "array",
        items: { kind: "ref", name: "CalculateTariffsOfferInfoDTO" },
      },
    },
    required: ["offers"],
  },
  CalculatedTariffDTO: {
    kind: "object",
    properties: {
      type: { kind: "ref", name: "CalculatedTariffType" },
      amount: { kind: "number" },
      currency: { kind: "ref", name: "CurrencyType" },
      parameters: {
        kind: "array",
        items: { kind: "ref", name: "TariffParameterDTO" },
      },
    },
    required: ["type", "parameters"],
  },
  CalculatedTariffType: {
    kind: "string",
    enum: [
      "AGENCY_COMMISSION",
      "PAYMENT_TRANSFER",
      "FEE",
      "DELIVERY_TO_CUSTOMER",
      "CROSSREGIONAL_DELIVERY",
      "EXPRESS_DELIVERY",
      "SORTING",
      "MIDDLE_MILE",
      "ITEM_BOOKING",
    ],
  },
  CampaignId: { kind: "number", integer: true, minimum: 1 },
  CurrencyType: {
    kind: "string",
    enum: [
      "RUR",
      "USD",
      "EUR",
      "UAH",
      "AUD",
      "GBP",
      "BYR",
      "BYN",
      "DKK",
      "ISK",
      "KZT",
      "CAD",
      "CNY",
      "NOK",
      "XDR",
      "SGD",
      "TRY",
      "SEK",
      "CHF",
      "JPY",
      "AZN",
      "ALL",
      "DZD",
      "AOA",
      "ARS",
      "AMD",
      "AFN",
      "BHD",
      "BGN",
      "BOB",
      "BWP",
      "BND",
      "BRL",
      "BIF",
      "HUF",
      "VEF",
      "KPW",
      "VND",
      "GMD",
      "GHS",
      "GNF",
      "HKD",
      "GEL",
      "AED",
      "EGP",
      "ZMK",
      "ILS",
      "INR",
      "IDR",
      "JOD",
      "IQD",
      "IRR",
      "YER",
      "QAR",
      "KES",
      "KGS",
      "COP",
      "CDF",
      "CRC",
      "KWD",
      "CUP",
      "LAK",
      "LVL",
      "SLL",
      "LBP",
      "LYD",
      "SZL",
      "LTL",
      "MUR",
      "MRO",
      "MKD",
      "MWK",
      "MGA",
      "MYR",
      "MAD",
      "MXN",
      "MZN",
      "MDL",
      "MNT",
      "NPR",
      "NGN",
      "NIO",
      "NZD",
      "OMR",
      "PKR",
      "PYG",
      "PEN",
      "PLN",
      "KHR",
      "SAR",
      "RON",
      "SCR",
      "SYP",
      "SKK",
      "SOS",
      "SDG",
      "SRD",
      "TJS",
      "THB",
      "TWD",
      "BDT",
      "TZS",
      "TND",
      "TMM",
      "UGX",
      "UZS",
      "UYU",
      "PHP",
      "DJF",
      "XAF",
      "XOF",
      "HRK",
      "CZK",
      "CLP",
      "LKR",
      "EEK",
      "ETB",
      "RSD",
      "ZAR",
      "KRW",
      "NAD",
      "TL",
      "UE",
    ],
  },
  PaymentFrequencyType: {
    kind: "string",
    enum: ["DAILY", "WEEKLY", "BIWEEKLY", "MONTHLY"],
  },
  SellingProgramType: {
    kind: "string",
    enum: ["FBY", "FBS", "DBS", "EXPRESS", "LAAS"],
  },
  TariffParameterDTO: {
    kind: "object",
    properties: { name: { kind: "string" }, value: { kind: "string" } },
    required: ["name", "value"],
  },
};
