// Generated runtime schemas for this Wildberries API domain.
import type { WbSchemaComponents } from "../schema.js";

export const financesComponents: WbSchemaComponents = {
  requestDownload: {
    kind: "object",
    properties: {
      params: {
        kind: "array",
        items: {
          kind: "object",
          properties: {
            extension: { kind: "string" },
            serviceName: { kind: "string" },
          },
          required: [],
        },
      },
    },
    required: [],
  },
  GetCategories: {
    kind: "object",
    properties: {
      data: {
        kind: "object",
        properties: {
          categories: {
            kind: "array",
            items: {
              kind: "object",
              properties: {
                name: { kind: "string" },
                title: { kind: "string" },
              },
              required: [],
            },
          },
        },
        required: [],
      },
    },
    required: [],
  },
  GetList: {
    kind: "object",
    properties: {
      data: {
        kind: "object",
        properties: {
          documents: {
            kind: "array",
            items: {
              kind: "object",
              properties: {
                serviceName: { kind: "string" },
                name: { kind: "string" },
                category: { kind: "string" },
                extensions: { kind: "array", items: { kind: "string" } },
                creationTime: { kind: "string" },
                viewed: { kind: "boolean" },
              },
              required: [],
            },
          },
        },
        required: [],
      },
    },
    required: [],
  },
  GetDoc: {
    kind: "object",
    properties: {
      data: {
        kind: "object",
        properties: {
          fileName: { kind: "string" },
          extension: { kind: "string" },
          document: { kind: "string" },
        },
        required: [],
      },
    },
    required: [],
  },
  GetDocs: {
    kind: "object",
    properties: {
      data: {
        kind: "object",
        properties: {
          fileName: { kind: "string" },
          extension: { kind: "string" },
          document: { kind: "string" },
        },
        required: [],
      },
    },
    required: [],
  },
  SalesReportListReq: {
    kind: "object",
    properties: {
      dateFrom: { kind: "string" },
      dateTo: { kind: "string" },
      limit: { kind: "number", integer: true, maximum: 1000 },
      offset: { kind: "number", integer: true },
      period: { kind: "string", enum: ["daily", "weekly"] },
    },
    required: ["dateFrom", "dateTo"],
  },
  SalesReportListRes: {
    kind: "object",
    properties: {
      reportId: { kind: "number", integer: true },
      sellerFinanceName: { kind: "string" },
      dateFrom: { kind: "string" },
      dateTo: { kind: "string" },
      createDate: { kind: "string" },
      currency: { kind: "string" },
      reportType: { kind: "number", integer: true, enum: [1, 2, 3] },
      retailAmountSum: { kind: "string" },
      forPaySum: { kind: "string" },
      avgSalePercent: { kind: "number" },
      deliveryServiceSum: { kind: "string" },
      paidStorageSum: { kind: "string" },
      paidAcceptanceSum: { kind: "string" },
      deductionSum: { kind: "string" },
      penaltySum: { kind: "string" },
      additionalPaymentSum: { kind: "string" },
      cashbackAmountSum: { kind: "string" },
      cashbackDiscountSum: { kind: "string" },
      cashbackCommissionChangeSum: { kind: "string" },
      paymentSchedule: { kind: "string" },
      bankPaymentSum: { kind: "string" },
    },
    required: [
      "reportId",
      "sellerFinanceName",
      "dateFrom",
      "dateTo",
      "createDate",
      "currency",
      "reportType",
      "retailAmountSum",
      "forPaySum",
      "avgSalePercent",
      "deliveryServiceSum",
      "paidStorageSum",
      "paidAcceptanceSum",
      "deductionSum",
      "penaltySum",
      "additionalPaymentSum",
      "cashbackAmountSum",
      "cashbackDiscountSum",
      "cashbackCommissionChangeSum",
      "paymentSchedule",
      "bankPaymentSum",
    ],
  },
  FinancialReportsDetailedReportIdReq: {
    kind: "object",
    properties: {
      limit: { kind: "number", integer: true, maximum: 100000 },
      rrdId: { kind: "number", integer: true },
      fields: { kind: "array", items: { kind: "string" } },
    },
    required: [],
  },
  SalesReportsDetailedReq: {
    kind: "object",
    properties: {
      dateFrom: { kind: "string" },
      dateTo: { kind: "string" },
      limit: { kind: "number", integer: true, maximum: 100000 },
      rrdId: { kind: "number", integer: true },
      period: { kind: "string", enum: ["daily", "weekly"] },
      fields: { kind: "array", items: { kind: "string" } },
    },
    required: ["dateFrom", "dateTo"],
  },
  SalesReportsDetailedRes: {
    kind: "object",
    properties: {
      reportId: { kind: "number", integer: true },
      dateFrom: { kind: "string" },
      dateTo: { kind: "string" },
      createDate: { kind: "string" },
      currency: { kind: "string" },
      reportType: { kind: "number", integer: true, enum: [1, 2, 3] },
      rrdId: { kind: "number", integer: true },
      giId: { kind: "number", integer: true },
      dlvPrc: { kind: "number" },
      fixTariffDateFrom: { kind: "string" },
      fixTariffDateTo: { kind: "string" },
      subjectName: { kind: "string" },
      nmId: { kind: "number", integer: true },
      brandName: { kind: "string" },
      vendorCode: { kind: "string" },
      title: { kind: "string" },
      techSize: { kind: "string" },
      sku: { kind: "string" },
      docTypeName: { kind: "string" },
      quantity: { kind: "number", integer: true },
      retailPrice: { kind: "string" },
      retailAmount: { kind: "string" },
      salePercent: { kind: "number", integer: true },
      commissionPercent: { kind: "number" },
      officeName: { kind: "string" },
      sellerOperName: { kind: "string" },
      orderDt: { kind: "string" },
      saleDt: { kind: "string" },
      rrDate: { kind: "string" },
      shkId: { kind: "number", integer: true },
      retailPriceWithDisc: { kind: "string" },
      deliveryAmount: { kind: "number", integer: true },
      returnAmount: { kind: "number", integer: true },
      deliveryService: { kind: "string" },
      giBoxTypeName: { kind: "string" },
      productDiscountForReport: { kind: "number" },
      sellerPromo: { kind: "string" },
      spp: { kind: "number" },
      kvwBase: { kind: "number" },
      kvw: { kind: "number" },
      supRatingUp: { kind: "number" },
      isKgvpV2: { kind: "number" },
      ppvzSalesCommission: { kind: "string" },
      forPay: { kind: "string" },
      ppvzReward: { kind: "string" },
      acquiringFee: { kind: "string" },
      acquiringPercent: { kind: "number" },
      paymentProcessing: { kind: "string" },
      acquiringBank: { kind: "string" },
      vw: { kind: "string" },
      vwNds: { kind: "string" },
      ppvzOfficeName: { kind: "string" },
      ppvzOfficeId: { kind: "number", integer: true },
      ppvzSupplierName: { kind: "string" },
      ppvzSupplierInn: { kind: "string" },
      declarationNumber: { kind: "string" },
      bonusTypeName: { kind: "string" },
      stickerId: { kind: "string" },
      country: { kind: "string" },
      srvDbs: { kind: "boolean" },
      penalty: { kind: "string" },
      additionalPayment: { kind: "string" },
      rebillLogisticCost: { kind: "string" },
      rebillLogisticOrg: { kind: "string" },
      paidStorage: { kind: "string" },
      deduction: { kind: "string" },
      paidAcceptance: { kind: "string" },
      orderId: { kind: "number", integer: true },
      kiz: { kind: "string" },
      isB2b: { kind: "boolean" },
      trbxId: { kind: "string" },
      installmentCofinancingAmount: { kind: "string" },
      wibesDiscountPercent: { kind: "number" },
      cashbackAmount: { kind: "string" },
      cashbackDiscount: { kind: "string" },
      cashbackCommissionChange: { kind: "string" },
      paymentSchedule: { kind: "string" },
      deliveryMethod: { kind: "string" },
      sellerPromoId: { kind: "number", integer: true },
      sellerPromoDiscount: { kind: "number" },
      loyaltyId: { kind: "number", integer: true },
      loyaltyDiscount: { kind: "number" },
      uuidPromocode: { kind: "string" },
      salePricePromocodeDiscountPrc: { kind: "number" },
      articleSubstitution: { kind: "string" },
      salePriceAffiliatedDiscountPrc: { kind: "number" },
      agencyVat: { kind: "number" },
      salePriceWholesaleDiscountPrc: { kind: "number" },
      b2bCustomerTin: { kind: "string" },
      paidWithSocialCertificate: { kind: "boolean" },
      orderUid: { kind: "string" },
      srid: { kind: "string" },
    },
    required: [
      "reportId",
      "dateFrom",
      "dateTo",
      "createDate",
      "currency",
      "reportType",
      "rrdId",
      "giId",
      "dlvPrc",
      "fixTariffDateFrom",
      "fixTariffDateTo",
      "subjectName",
      "nmId",
      "brandName",
      "vendorCode",
      "title",
      "techSize",
      "sku",
      "docTypeName",
      "quantity",
      "retailPrice",
      "retailAmount",
      "salePercent",
      "commissionPercent",
      "officeName",
      "sellerOperName",
      "orderDt",
      "saleDt",
      "rrDate",
      "shkId",
      "retailPriceWithDisc",
      "deliveryAmount",
      "returnAmount",
      "deliveryService",
      "giBoxTypeName",
      "productDiscountForReport",
      "sellerPromo",
      "spp",
      "kvwBase",
      "kvw",
      "supRatingUp",
      "isKgvpV2",
      "ppvzSalesCommission",
      "forPay",
      "ppvzReward",
      "acquiringFee",
      "acquiringPercent",
      "paymentProcessing",
      "acquiringBank",
      "vw",
      "vwNds",
      "ppvzOfficeName",
      "ppvzOfficeId",
      "ppvzSupplierName",
      "ppvzSupplierInn",
      "declarationNumber",
      "stickerId",
      "country",
      "srvDbs",
      "penalty",
      "additionalPayment",
      "rebillLogisticCost",
      "paidStorage",
      "deduction",
      "paidAcceptance",
      "orderId",
      "isB2b",
      "trbxId",
      "installmentCofinancingAmount",
      "wibesDiscountPercent",
      "cashbackAmount",
      "cashbackDiscount",
      "cashbackCommissionChange",
      "paymentSchedule",
      "deliveryMethod",
      "sellerPromoId",
      "sellerPromoDiscount",
      "loyaltyId",
      "loyaltyDiscount",
      "uuidPromocode",
      "salePricePromocodeDiscountPrc",
      "articleSubstitution",
      "salePriceAffiliatedDiscountPrc",
      "salePriceWholesaleDiscountPrc",
      "b2bCustomerTin",
      "paidWithSocialCertificate",
      "orderUid",
      "srid",
    ],
  },
  AcquiringReportListReq: {
    kind: "object",
    properties: {
      dateFrom: { kind: "string" },
      dateTo: { kind: "string" },
      limit: { kind: "number", integer: true, maximum: 1000 },
      offset: { kind: "number", integer: true },
    },
    required: ["dateFrom", "dateTo"],
  },
  AcquiringReportListRes: {
    kind: "object",
    properties: {
      reportId: { kind: "number", integer: true },
      sellerFinanceName: { kind: "string" },
      dateFrom: { kind: "string" },
      dateTo: { kind: "string" },
      createDate: { kind: "string" },
      currency: { kind: "string" },
      acquiringFeeSum: { kind: "string" },
      acquiringFeeVatSum: { kind: "string" },
    },
    required: [
      "reportId",
      "sellerFinanceName",
      "dateFrom",
      "dateTo",
      "createDate",
      "currency",
      "acquiringFeeSum",
      "acquiringFeeVatSum",
    ],
  },
  AcquiringReportsDetailedReq: {
    kind: "object",
    properties: {
      dateFrom: { kind: "string" },
      dateTo: { kind: "string" },
      limit: { kind: "number", integer: true, maximum: 100000 },
      rrdId: { kind: "number", integer: true },
      fields: { kind: "array", items: { kind: "string" } },
    },
    required: ["dateFrom", "dateTo"],
  },
  AcquiringReportsDetailedRes: {
    kind: "object",
    properties: {
      rrdId: { kind: "number", integer: true },
      reportId: { kind: "number", integer: true },
      acqDate: { kind: "string" },
      acquiringBank: { kind: "string" },
      tin: { kind: "string" },
      taxRegistrationReasonCode: { kind: "string" },
      saleDate: { kind: "string" },
      srid: { kind: "string" },
      docTypeName: { kind: "string" },
      nmId: { kind: "number", integer: true },
      retailAmount: { kind: "string" },
      acquiringFee: { kind: "string" },
      acquiringFeeVat: { kind: "string" },
      invoiceNumber: { kind: "string" },
      invoiceDate: { kind: "string" },
      shkId: { kind: "number", integer: true },
      currency: { kind: "string" },
    },
    required: [
      "reportId",
      "currency",
      "rrdId",
      "nmId",
      "docTypeName",
      "retailAmount",
      "saleDate",
      "acqDate",
      "shkId",
      "acquiringFee",
      "acquiringFeeVat",
      "acquiringBank",
      "tin",
      "taxRegistrationReasonCode",
      "invoiceNumber",
      "invoiceDate",
      "srid",
    ],
  },
};
