// Generated runtime schemas for this Wildberries API domain.
import type { WbSchemaComponents } from "../schema.js";

export const reportsComponents: WbSchemaComponents = {
  OrdersItem: {
    kind: "object",
    properties: {
      date: { kind: "string" },
      lastChangeDate: { kind: "string" },
      warehouseName: { kind: "string", maxLength: 50 },
      warehouseType: { kind: "string", enum: ["Склад WB", "Склад продавца"] },
      countryName: { kind: "string", maxLength: 200 },
      oblastOkrugName: { kind: "string", maxLength: 200 },
      regionName: { kind: "string", maxLength: 200 },
      supplierArticle: { kind: "string", maxLength: 75 },
      nmId: { kind: "number", integer: true },
      barcode: { kind: "string", maxLength: 30 },
      category: { kind: "string", maxLength: 50 },
      subject: { kind: "string", maxLength: 50 },
      brand: { kind: "string", maxLength: 50 },
      techSize: { kind: "string", maxLength: 30 },
      incomeID: { kind: "number", integer: true },
      isSupply: { kind: "boolean" },
      isRealization: { kind: "boolean" },
      totalPrice: { kind: "number" },
      discountPercent: { kind: "number", integer: true },
      spp: { kind: "number" },
      finishedPrice: { kind: "number" },
      priceWithDisc: { kind: "number" },
      isCancel: { kind: "boolean" },
      cancelDate: { kind: "string" },
      sticker: { kind: "string" },
      gNumber: { kind: "string", maxLength: 50 },
      srid: { kind: "string" },
    },
    required: [],
  },
  SalesItem: {
    kind: "object",
    properties: {
      date: { kind: "string" },
      lastChangeDate: { kind: "string" },
      warehouseName: { kind: "string", maxLength: 50 },
      warehouseType: { kind: "string", enum: ["Склад WB", "Склад продавца"] },
      countryName: { kind: "string", maxLength: 200 },
      oblastOkrugName: { kind: "string", maxLength: 200 },
      regionName: { kind: "string", maxLength: 200 },
      supplierArticle: { kind: "string", maxLength: 75 },
      nmId: { kind: "number", integer: true },
      barcode: { kind: "string", maxLength: 30 },
      category: { kind: "string", maxLength: 50 },
      subject: { kind: "string", maxLength: 50 },
      brand: { kind: "string", maxLength: 50 },
      techSize: { kind: "string", maxLength: 30 },
      incomeID: { kind: "number", integer: true },
      isSupply: { kind: "boolean" },
      isRealization: { kind: "boolean" },
      totalPrice: { kind: "number" },
      discountPercent: { kind: "number", integer: true },
      spp: { kind: "number" },
      paymentSaleAmount: { kind: "number", integer: true },
      forPay: { kind: "number" },
      finishedPrice: { kind: "number" },
      priceWithDisc: { kind: "number" },
      saleID: { kind: "string", maxLength: 15 },
      sticker: { kind: "string" },
      gNumber: { kind: "string", maxLength: 50 },
      srid: { kind: "string" },
    },
    required: [],
  },
  responseErrorStatistics: {
    kind: "object",
    properties: { errors: { kind: "array", items: { kind: "string" } } },
    required: [],
  },
  responseErrorStatistics2: {
    kind: "object",
    properties: { errors: { kind: "string" } },
    required: [],
  },
  ExciseReportRequest: {
    kind: "object",
    properties: {
      countries: {
        kind: "array",
        items: { kind: "string", enum: ["AM", "BY", "KG", "KZ", "RU", "UZ"] },
      },
    },
    required: [],
  },
  ExciseReportResponse: {
    kind: "object",
    properties: {
      response: { kind: "ref", name: "models.ExciseReportResponse" },
    },
    required: [],
  },
  "models.ExciseReportResponse": {
    kind: "object",
    properties: {
      data: { kind: "ref", name: "models.ExciseReportResponseData" },
    },
    required: [],
  },
  "models.ExciseReportResponseData": {
    kind: "array",
    items: {
      kind: "object",
      properties: {
        name: { kind: "string" },
        price: { kind: "number" },
        currency_name_short: { kind: "string" },
        excise_short: { kind: "string" },
        barcode: { kind: "string" },
        nm_id: { kind: "number", integer: true },
        operation_type_id: { kind: "number", integer: true },
        fiscal_doc_number: { kind: "number", integer: true },
        fiscal_dt: { kind: "string" },
        fiscal_drive_number: { kind: "string" },
        rid: { kind: "number", integer: true },
        srid: { kind: "string" },
      },
      required: [],
    },
  },
  MeasurementPenalties: {
    kind: "object",
    properties: {
      data: {
        kind: "object",
        properties: {
          reports: {
            kind: "array",
            items: {
              kind: "object",
              properties: {
                nmId: { kind: "number", integer: true },
                subjectName: { kind: "string" },
                dimId: { kind: "number", integer: true },
                prcOver: { kind: "number" },
                volume: { kind: "number" },
                width: { kind: "number", integer: true },
                length: { kind: "number", integer: true },
                height: { kind: "number", integer: true },
                volumeSup: { kind: "number" },
                widthSup: { kind: "number", integer: true },
                lengthSup: { kind: "number", integer: true },
                heightSup: { kind: "number", integer: true },
                photoUrls: { kind: "array", items: { kind: "string" } },
                dtBonus: { kind: "string" },
                isValid: { kind: "boolean" },
                isValidDt: { kind: "string" },
                reversalAmount: { kind: "number" },
                penaltyAmount: { kind: "number" },
              },
              required: [],
            },
          },
          total: { kind: "number", integer: true },
        },
        required: ["reports", "total"],
      },
    },
    required: ["data"],
  },
  WHM: {
    kind: "object",
    properties: {
      data: {
        kind: "object",
        properties: {
          reports: {
            kind: "array",
            items: {
              kind: "object",
              properties: {
                nmId: { kind: "number", integer: true },
                subjectName: { kind: "string" },
                dimId: { kind: "number", integer: true },
                volume: { kind: "number" },
                width: { kind: "number", integer: true },
                length: { kind: "number", integer: true },
                height: { kind: "number", integer: true },
                photoUrls: { kind: "array", items: { kind: "string" } },
                dt: { kind: "string" },
              },
              required: [],
            },
          },
          total: { kind: "number", integer: true },
        },
        required: ["reports", "total"],
      },
    },
    required: ["data"],
  },
  Response400Retentions: {
    kind: "object",
    properties: {
      title: { kind: "string" },
      status: { kind: "number", integer: true },
      detail: { kind: "string" },
      requestId: { kind: "string" },
      origin: { kind: "string" },
    },
    required: [],
  },
  Response403Retentions: {
    kind: "object",
    properties: {
      title: { kind: "string" },
      status: { kind: "number", integer: true },
      detail: { kind: "string" },
      requestId: { kind: "string" },
      origin: { kind: "string" },
    },
    required: [],
  },
  ResponsePaidStorage: {
    kind: "array",
    items: {
      kind: "object",
      properties: {
        date: { kind: "string" },
        logWarehouseCoef: { kind: "number" },
        officeId: { kind: "number", integer: true },
        warehouse: { kind: "string" },
        warehouseCoef: { kind: "number" },
        giId: { kind: "number", integer: true },
        chrtId: { kind: "number", integer: true },
        size: { kind: "string" },
        barcode: { kind: "string" },
        subject: { kind: "string" },
        brand: { kind: "string" },
        vendorCode: { kind: "string" },
        nmId: { kind: "number", integer: true },
        volume: { kind: "number" },
        calcType: { kind: "string" },
        warehousePrice: { kind: "number" },
        barcodesCount: { kind: "number", integer: true },
        palletPlaceCode: { kind: "number", integer: true },
        palletCount: { kind: "number" },
        originalDate: { kind: "string" },
        loyaltyDiscount: { kind: "number" },
        tariffFixDate: { kind: "string" },
        tariffLowerDate: { kind: "string" },
      },
      required: [],
    },
  },
  GetTasksResponse: {
    kind: "object",
    properties: { data: { kind: "ref", name: "GetTasksResponseData" } },
    required: [],
  },
  GetTasksResponseData: {
    kind: "object",
    properties: { id: { kind: "string" }, status: { kind: "string" } },
    required: [],
  },
  CreateTaskResponse: {
    kind: "object",
    properties: { data: { kind: "ref", name: "CreateTaskResponseData" } },
    required: [],
  },
  CreateTaskResponseData: {
    kind: "object",
    properties: { taskId: { kind: "string" } },
    required: [],
  },
  "4xxResponse": {
    kind: "object",
    properties: {
      detail: { kind: "string" },
      origin: { kind: "string" },
      requestId: { kind: "string" },
      title: { kind: "string" },
    },
    required: [],
  },
};
