export type OzonCargoTransportOperationStatus =
  | "SUCCESS"
  | "IN_PROGRESS"
  | "FAILED";
export type OzonCargoTransportActivateError =
  | "OPERATION_NOT_FOUND"
  | "SUPPLY_IS_FINALIZED"
  | "CAN_NOT_EDIT_TAG"
  | "UNDEFINED";
export type OzonCargoTransportCreateError =
  | "SUPPLY_NOT_FOUND"
  | "WAREHOUSE_LIMITS_EXCEED"
  | "SUPPLY_DOES_NOT_BELONG_TO_THE_CONTRACTOR"
  | "SUPPLY_DOES_NOT_BELONG_TO_THE_COMPANY"
  | "PALLET_SUPPLY_CONTAINS_BOXES"
  | "SUPPLY_CARGOES_IS_FINALIZED"
  | "SUPPLY_CARGOES_LOCKED"
  | "OPERATION_NOT_FOUND"
  | "ETTN_IS_UPLOADED"
  | "BOX_SUPPLY_CONTAINS_PALLETS"
  | "UNDEFINED";
export type OzonCargoTransportBindError =
  | "OPERATION_NOT_FOUND"
  | "OPERATION_FAILED"
  | "SUPPLY_NOT_FOUND"
  | "SUPPLY_DOES_NOT_BELONG_TO_COMPANY"
  | "SUPPLY_DOES_NOT_BELONG_TO_CONTRACTOR"
  | "TRANSPORT_CARGOES_NOT_ENABLED_FOR_SUPPLY"
  | "INVALID_SUPPLY_STATE"
  | "SUPPLY_IS_FINALIZED"
  | "CARGO_IDS_NOT_FOUND"
  | "TRANSPORT_CARGO_IDS_NOT_FOUND"
  | "ETTN_IS_UPLOADED";
export interface OzonCargoOperationResponse {
  readonly operation_id?: string;
}
