export interface OzonFbpDirectDraftResponse {
  readonly draft_id?: number;
  readonly row_version?: number;
  readonly supply_id?: string;
}
export type OzonFbpDraftValidationError =
  | "ERROR_TYPE_UNSPECIFIED"
  | "ORDER_DRAFT_LOCKED"
  | "DELIVERY_DRIVER_NAME_LENGTH_MAXIMUM_REACHED"
  | "DELIVERY_VEHICLE_GENRE_LENGTH_MAXIMUM_REACHED"
  | "DELIVERY_VEHICLE_REGISTRATION_PLATE_LENGTH_MAXIMUM_REACHED"
  | "DELIVERY_TPL_NAME_LENGTH_MAXIMUM_REACHED"
  | "DELIVERY_TRACKING_NUMBER_LENGTH_MAXIMUM_REACHED"
  | "DELIVERY_DRIVER_NAME_EMPTY"
  | "DELIVERY_VEHICLE_GENRE_EMPTY"
  | "DELIVERY_VEHICLE_REGISTRATION_PLATE_EMPTY"
  | "DELIVERY_TPL_NAME_EMPTY"
  | "DELIVERY_TRACKING_NUMBER_EMPTY"
  | "INVALID_BUSINESS_FLOW"
  | "SUPPLY_TYPE_NOT_SUPPORTED"
  | "INVALID_STATE";
